// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SyncPackage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_SyncPackage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_SyncPackage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "BattleSyncPackage.pb.h"
#include "LobbySyncPackage.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SyncPackage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_SyncPackage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_SyncPackage_2eproto;
namespace SyncPackage {
class SyncPackage;
struct SyncPackageDefaultTypeInternal;
extern SyncPackageDefaultTypeInternal _SyncPackage_default_instance_;
}  // namespace SyncPackage
PROTOBUF_NAMESPACE_OPEN
template<> ::SyncPackage::SyncPackage* Arena::CreateMaybeMessage<::SyncPackage::SyncPackage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace SyncPackage {

// ===================================================================

class SyncPackage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SyncPackage.SyncPackage) */ {
 public:
  inline SyncPackage() : SyncPackage(nullptr) {}
  ~SyncPackage() override;
  explicit PROTOBUF_CONSTEXPR SyncPackage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SyncPackage(const SyncPackage& from);
  SyncPackage(SyncPackage&& from) noexcept
    : SyncPackage() {
    *this = ::std::move(from);
  }

  inline SyncPackage& operator=(const SyncPackage& from) {
    CopyFrom(from);
    return *this;
  }
  inline SyncPackage& operator=(SyncPackage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SyncPackage& default_instance() {
    return *internal_default_instance();
  }
  enum ContentCase {
    kBattlePackage = 1,
    kLobbySync = 2,
    CONTENT_NOT_SET = 0,
  };

  static inline const SyncPackage* internal_default_instance() {
    return reinterpret_cast<const SyncPackage*>(
               &_SyncPackage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SyncPackage& a, SyncPackage& b) {
    a.Swap(&b);
  }
  inline void Swap(SyncPackage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SyncPackage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SyncPackage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SyncPackage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SyncPackage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SyncPackage& from) {
    SyncPackage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SyncPackage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SyncPackage.SyncPackage";
  }
  protected:
  explicit SyncPackage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBattlePackageFieldNumber = 1,
    kLobbySyncFieldNumber = 2,
  };
  // .BattleSyncPackage.BattleSync battlePackage = 1;
  bool has_battlepackage() const;
  private:
  bool _internal_has_battlepackage() const;
  public:
  void clear_battlepackage();
  const ::BattleSyncPackage::BattleSync& battlepackage() const;
  PROTOBUF_NODISCARD ::BattleSyncPackage::BattleSync* release_battlepackage();
  ::BattleSyncPackage::BattleSync* mutable_battlepackage();
  void set_allocated_battlepackage(::BattleSyncPackage::BattleSync* battlepackage);
  private:
  const ::BattleSyncPackage::BattleSync& _internal_battlepackage() const;
  ::BattleSyncPackage::BattleSync* _internal_mutable_battlepackage();
  public:
  void unsafe_arena_set_allocated_battlepackage(
      ::BattleSyncPackage::BattleSync* battlepackage);
  ::BattleSyncPackage::BattleSync* unsafe_arena_release_battlepackage();

  // .LobbySyncPackage.LobbySync lobbySync = 2;
  bool has_lobbysync() const;
  private:
  bool _internal_has_lobbysync() const;
  public:
  void clear_lobbysync();
  const ::LobbySyncPackage::LobbySync& lobbysync() const;
  PROTOBUF_NODISCARD ::LobbySyncPackage::LobbySync* release_lobbysync();
  ::LobbySyncPackage::LobbySync* mutable_lobbysync();
  void set_allocated_lobbysync(::LobbySyncPackage::LobbySync* lobbysync);
  private:
  const ::LobbySyncPackage::LobbySync& _internal_lobbysync() const;
  ::LobbySyncPackage::LobbySync* _internal_mutable_lobbysync();
  public:
  void unsafe_arena_set_allocated_lobbysync(
      ::LobbySyncPackage::LobbySync* lobbysync);
  ::LobbySyncPackage::LobbySync* unsafe_arena_release_lobbysync();

  void clear_content();
  ContentCase content_case() const;
  // @@protoc_insertion_point(class_scope:SyncPackage.SyncPackage)
 private:
  class _Internal;
  void set_has_battlepackage();
  void set_has_lobbysync();

  inline bool has_content() const;
  inline void clear_has_content();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union ContentUnion {
      constexpr ContentUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::BattleSyncPackage::BattleSync* battlepackage_;
      ::LobbySyncPackage::LobbySync* lobbysync_;
    } content_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SyncPackage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SyncPackage

// .BattleSyncPackage.BattleSync battlePackage = 1;
inline bool SyncPackage::_internal_has_battlepackage() const {
  return content_case() == kBattlePackage;
}
inline bool SyncPackage::has_battlepackage() const {
  return _internal_has_battlepackage();
}
inline void SyncPackage::set_has_battlepackage() {
  _impl_._oneof_case_[0] = kBattlePackage;
}
inline ::BattleSyncPackage::BattleSync* SyncPackage::release_battlepackage() {
  // @@protoc_insertion_point(field_release:SyncPackage.SyncPackage.battlePackage)
  if (_internal_has_battlepackage()) {
    clear_has_content();
    ::BattleSyncPackage::BattleSync* temp = _impl_.content_.battlepackage_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.battlepackage_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::BattleSyncPackage::BattleSync& SyncPackage::_internal_battlepackage() const {
  return _internal_has_battlepackage()
      ? *_impl_.content_.battlepackage_
      : reinterpret_cast< ::BattleSyncPackage::BattleSync&>(::BattleSyncPackage::_BattleSync_default_instance_);
}
inline const ::BattleSyncPackage::BattleSync& SyncPackage::battlepackage() const {
  // @@protoc_insertion_point(field_get:SyncPackage.SyncPackage.battlePackage)
  return _internal_battlepackage();
}
inline ::BattleSyncPackage::BattleSync* SyncPackage::unsafe_arena_release_battlepackage() {
  // @@protoc_insertion_point(field_unsafe_arena_release:SyncPackage.SyncPackage.battlePackage)
  if (_internal_has_battlepackage()) {
    clear_has_content();
    ::BattleSyncPackage::BattleSync* temp = _impl_.content_.battlepackage_;
    _impl_.content_.battlepackage_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void SyncPackage::unsafe_arena_set_allocated_battlepackage(::BattleSyncPackage::BattleSync* battlepackage) {
  clear_content();
  if (battlepackage) {
    set_has_battlepackage();
    _impl_.content_.battlepackage_ = battlepackage;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SyncPackage.SyncPackage.battlePackage)
}
inline ::BattleSyncPackage::BattleSync* SyncPackage::_internal_mutable_battlepackage() {
  if (!_internal_has_battlepackage()) {
    clear_content();
    set_has_battlepackage();
    _impl_.content_.battlepackage_ = CreateMaybeMessage< ::BattleSyncPackage::BattleSync >(GetArenaForAllocation());
  }
  return _impl_.content_.battlepackage_;
}
inline ::BattleSyncPackage::BattleSync* SyncPackage::mutable_battlepackage() {
  ::BattleSyncPackage::BattleSync* _msg = _internal_mutable_battlepackage();
  // @@protoc_insertion_point(field_mutable:SyncPackage.SyncPackage.battlePackage)
  return _msg;
}

// .LobbySyncPackage.LobbySync lobbySync = 2;
inline bool SyncPackage::_internal_has_lobbysync() const {
  return content_case() == kLobbySync;
}
inline bool SyncPackage::has_lobbysync() const {
  return _internal_has_lobbysync();
}
inline void SyncPackage::set_has_lobbysync() {
  _impl_._oneof_case_[0] = kLobbySync;
}
inline ::LobbySyncPackage::LobbySync* SyncPackage::release_lobbysync() {
  // @@protoc_insertion_point(field_release:SyncPackage.SyncPackage.lobbySync)
  if (_internal_has_lobbysync()) {
    clear_has_content();
    ::LobbySyncPackage::LobbySync* temp = _impl_.content_.lobbysync_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.lobbysync_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::LobbySyncPackage::LobbySync& SyncPackage::_internal_lobbysync() const {
  return _internal_has_lobbysync()
      ? *_impl_.content_.lobbysync_
      : reinterpret_cast< ::LobbySyncPackage::LobbySync&>(::LobbySyncPackage::_LobbySync_default_instance_);
}
inline const ::LobbySyncPackage::LobbySync& SyncPackage::lobbysync() const {
  // @@protoc_insertion_point(field_get:SyncPackage.SyncPackage.lobbySync)
  return _internal_lobbysync();
}
inline ::LobbySyncPackage::LobbySync* SyncPackage::unsafe_arena_release_lobbysync() {
  // @@protoc_insertion_point(field_unsafe_arena_release:SyncPackage.SyncPackage.lobbySync)
  if (_internal_has_lobbysync()) {
    clear_has_content();
    ::LobbySyncPackage::LobbySync* temp = _impl_.content_.lobbysync_;
    _impl_.content_.lobbysync_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void SyncPackage::unsafe_arena_set_allocated_lobbysync(::LobbySyncPackage::LobbySync* lobbysync) {
  clear_content();
  if (lobbysync) {
    set_has_lobbysync();
    _impl_.content_.lobbysync_ = lobbysync;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SyncPackage.SyncPackage.lobbySync)
}
inline ::LobbySyncPackage::LobbySync* SyncPackage::_internal_mutable_lobbysync() {
  if (!_internal_has_lobbysync()) {
    clear_content();
    set_has_lobbysync();
    _impl_.content_.lobbysync_ = CreateMaybeMessage< ::LobbySyncPackage::LobbySync >(GetArenaForAllocation());
  }
  return _impl_.content_.lobbysync_;
}
inline ::LobbySyncPackage::LobbySync* SyncPackage::mutable_lobbysync() {
  ::LobbySyncPackage::LobbySync* _msg = _internal_mutable_lobbysync();
  // @@protoc_insertion_point(field_mutable:SyncPackage.SyncPackage.lobbySync)
  return _msg;
}

inline bool SyncPackage::has_content() const {
  return content_case() != CONTENT_NOT_SET;
}
inline void SyncPackage::clear_has_content() {
  _impl_._oneof_case_[0] = CONTENT_NOT_SET;
}
inline SyncPackage::ContentCase SyncPackage::content_case() const {
  return SyncPackage::ContentCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace SyncPackage

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_SyncPackage_2eproto
