// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleSyncPackage.proto

#include "BattleSyncPackage.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace BattleSyncPackage {
PROTOBUF_CONSTEXPR BattleSyncRequest::BattleSyncRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.movedir_)*/nullptr
  , /*decltype(_impl_.position_)*/nullptr
  , /*decltype(_impl_.eulaangle_)*/nullptr
  , /*decltype(_impl_.playerid_)*/0u
  , /*decltype(_impl_.tick_)*/0u
  , /*decltype(_impl_.yaw_)*/0
  , /*decltype(_impl_.pitch_)*/0
  , /*decltype(_impl_.jump_)*/false
  , /*decltype(_impl_.activeskill_)*/false
  , /*decltype(_impl_.ultimateskill_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BattleSyncRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BattleSyncRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BattleSyncRequestDefaultTypeInternal() {}
  union {
    BattleSyncRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BattleSyncRequestDefaultTypeInternal _BattleSyncRequest_default_instance_;
PROTOBUF_CONSTEXPR BattleSyncResponse::BattleSyncResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.states_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BattleSyncResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BattleSyncResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BattleSyncResponseDefaultTypeInternal() {}
  union {
    BattleSyncResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BattleSyncResponseDefaultTypeInternal _BattleSyncResponse_default_instance_;
PROTOBUF_CONSTEXPR PlayerState::PlayerState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.movedir_)*/nullptr
  , /*decltype(_impl_.position_)*/nullptr
  , /*decltype(_impl_.eulaangle_)*/nullptr
  , /*decltype(_impl_.playerid_)*/0u
  , /*decltype(_impl_.tick_)*/0u
  , /*decltype(_impl_.yaw_)*/0
  , /*decltype(_impl_.pitch_)*/0
  , /*decltype(_impl_.jump_)*/false
  , /*decltype(_impl_.activeskill_)*/false
  , /*decltype(_impl_.ultimateskill_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerStateDefaultTypeInternal() {}
  union {
    PlayerState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerStateDefaultTypeInternal _PlayerState_default_instance_;
}  // namespace BattleSyncPackage
static ::_pb::Metadata file_level_metadata_BattleSyncPackage_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_BattleSyncPackage_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_BattleSyncPackage_2eproto = nullptr;

const uint32_t TableStruct_BattleSyncPackage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::BattleSyncRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::BattleSyncRequest, _impl_.playerid_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::BattleSyncRequest, _impl_.tick_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::BattleSyncRequest, _impl_.movedir_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::BattleSyncRequest, _impl_.jump_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::BattleSyncRequest, _impl_.yaw_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::BattleSyncRequest, _impl_.pitch_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::BattleSyncRequest, _impl_.activeskill_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::BattleSyncRequest, _impl_.ultimateskill_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::BattleSyncRequest, _impl_.position_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::BattleSyncRequest, _impl_.eulaangle_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::BattleSyncResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::BattleSyncResponse, _impl_.states_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::PlayerState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::PlayerState, _impl_.playerid_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::PlayerState, _impl_.tick_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::PlayerState, _impl_.movedir_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::PlayerState, _impl_.jump_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::PlayerState, _impl_.yaw_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::PlayerState, _impl_.pitch_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::PlayerState, _impl_.activeskill_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::PlayerState, _impl_.ultimateskill_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::PlayerState, _impl_.position_),
  PROTOBUF_FIELD_OFFSET(::BattleSyncPackage::PlayerState, _impl_.eulaangle_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::BattleSyncPackage::BattleSyncRequest)},
  { 16, -1, -1, sizeof(::BattleSyncPackage::BattleSyncResponse)},
  { 23, -1, -1, sizeof(::BattleSyncPackage::PlayerState)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::BattleSyncPackage::_BattleSyncRequest_default_instance_._instance,
  &::BattleSyncPackage::_BattleSyncResponse_default_instance_._instance,
  &::BattleSyncPackage::_PlayerState_default_instance_._instance,
};

const char descriptor_table_protodef_BattleSyncPackage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027BattleSyncPackage.proto\022\021BattleSyncPac"
  "kage\032\017UnityMath.proto\"\376\001\n\021BattleSyncRequ"
  "est\022\020\n\010playerID\030\001 \001(\r\022\014\n\004tick\030\002 \001(\r\022$\n\007m"
  "oveDir\030\003 \001(\0132\023.UnityMath.Vector2D\022\014\n\004jum"
  "p\030\004 \001(\010\022\013\n\003yaw\030\005 \001(\002\022\r\n\005pitch\030\006 \001(\002\022\023\n\013a"
  "ctiveSkill\030\007 \001(\010\022\025\n\rultimateSkill\030\010 \001(\010\022"
  "%\n\010position\030\t \001(\0132\023.UnityMath.Vector3D\022&"
  "\n\teulaAngle\030\n \001(\0132\023.UnityMath.Vector3D\"D"
  "\n\022BattleSyncResponse\022.\n\006states\030\001 \003(\0132\036.B"
  "attleSyncPackage.PlayerState\"\370\001\n\013PlayerS"
  "tate\022\020\n\010playerID\030\001 \001(\r\022\014\n\004tick\030\002 \001(\r\022$\n\007"
  "moveDir\030\003 \001(\0132\023.UnityMath.Vector2D\022\014\n\004ju"
  "mp\030\004 \001(\010\022\013\n\003yaw\030\005 \001(\002\022\r\n\005pitch\030\006 \001(\002\022\023\n\013"
  "activeSkill\030\007 \001(\010\022\025\n\rultimateSkill\030\010 \001(\010"
  "\022%\n\010position\030\t \001(\0132\023.UnityMath.Vector3D\022"
  "&\n\teulaAngle\030\n \001(\0132\023.UnityMath.Vector3Db"
  "\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_BattleSyncPackage_2eproto_deps[1] = {
  &::descriptor_table_UnityMath_2eproto,
};
static ::_pbi::once_flag descriptor_table_BattleSyncPackage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_BattleSyncPackage_2eproto = {
    false, false, 647, descriptor_table_protodef_BattleSyncPackage_2eproto,
    "BattleSyncPackage.proto",
    &descriptor_table_BattleSyncPackage_2eproto_once, descriptor_table_BattleSyncPackage_2eproto_deps, 1, 3,
    schemas, file_default_instances, TableStruct_BattleSyncPackage_2eproto::offsets,
    file_level_metadata_BattleSyncPackage_2eproto, file_level_enum_descriptors_BattleSyncPackage_2eproto,
    file_level_service_descriptors_BattleSyncPackage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_BattleSyncPackage_2eproto_getter() {
  return &descriptor_table_BattleSyncPackage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_BattleSyncPackage_2eproto(&descriptor_table_BattleSyncPackage_2eproto);
namespace BattleSyncPackage {

// ===================================================================

class BattleSyncRequest::_Internal {
 public:
  static const ::UnityMath::Vector2D& movedir(const BattleSyncRequest* msg);
  static const ::UnityMath::Vector3D& position(const BattleSyncRequest* msg);
  static const ::UnityMath::Vector3D& eulaangle(const BattleSyncRequest* msg);
};

const ::UnityMath::Vector2D&
BattleSyncRequest::_Internal::movedir(const BattleSyncRequest* msg) {
  return *msg->_impl_.movedir_;
}
const ::UnityMath::Vector3D&
BattleSyncRequest::_Internal::position(const BattleSyncRequest* msg) {
  return *msg->_impl_.position_;
}
const ::UnityMath::Vector3D&
BattleSyncRequest::_Internal::eulaangle(const BattleSyncRequest* msg) {
  return *msg->_impl_.eulaangle_;
}
void BattleSyncRequest::clear_movedir() {
  if (GetArenaForAllocation() == nullptr && _impl_.movedir_ != nullptr) {
    delete _impl_.movedir_;
  }
  _impl_.movedir_ = nullptr;
}
void BattleSyncRequest::clear_position() {
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
}
void BattleSyncRequest::clear_eulaangle() {
  if (GetArenaForAllocation() == nullptr && _impl_.eulaangle_ != nullptr) {
    delete _impl_.eulaangle_;
  }
  _impl_.eulaangle_ = nullptr;
}
BattleSyncRequest::BattleSyncRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:BattleSyncPackage.BattleSyncRequest)
}
BattleSyncRequest::BattleSyncRequest(const BattleSyncRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BattleSyncRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.movedir_){nullptr}
    , decltype(_impl_.position_){nullptr}
    , decltype(_impl_.eulaangle_){nullptr}
    , decltype(_impl_.playerid_){}
    , decltype(_impl_.tick_){}
    , decltype(_impl_.yaw_){}
    , decltype(_impl_.pitch_){}
    , decltype(_impl_.jump_){}
    , decltype(_impl_.activeskill_){}
    , decltype(_impl_.ultimateskill_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_movedir()) {
    _this->_impl_.movedir_ = new ::UnityMath::Vector2D(*from._impl_.movedir_);
  }
  if (from._internal_has_position()) {
    _this->_impl_.position_ = new ::UnityMath::Vector3D(*from._impl_.position_);
  }
  if (from._internal_has_eulaangle()) {
    _this->_impl_.eulaangle_ = new ::UnityMath::Vector3D(*from._impl_.eulaangle_);
  }
  ::memcpy(&_impl_.playerid_, &from._impl_.playerid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.ultimateskill_) -
    reinterpret_cast<char*>(&_impl_.playerid_)) + sizeof(_impl_.ultimateskill_));
  // @@protoc_insertion_point(copy_constructor:BattleSyncPackage.BattleSyncRequest)
}

inline void BattleSyncRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.movedir_){nullptr}
    , decltype(_impl_.position_){nullptr}
    , decltype(_impl_.eulaangle_){nullptr}
    , decltype(_impl_.playerid_){0u}
    , decltype(_impl_.tick_){0u}
    , decltype(_impl_.yaw_){0}
    , decltype(_impl_.pitch_){0}
    , decltype(_impl_.jump_){false}
    , decltype(_impl_.activeskill_){false}
    , decltype(_impl_.ultimateskill_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BattleSyncRequest::~BattleSyncRequest() {
  // @@protoc_insertion_point(destructor:BattleSyncPackage.BattleSyncRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BattleSyncRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.movedir_;
  if (this != internal_default_instance()) delete _impl_.position_;
  if (this != internal_default_instance()) delete _impl_.eulaangle_;
}

void BattleSyncRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BattleSyncRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:BattleSyncPackage.BattleSyncRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.movedir_ != nullptr) {
    delete _impl_.movedir_;
  }
  _impl_.movedir_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.eulaangle_ != nullptr) {
    delete _impl_.eulaangle_;
  }
  _impl_.eulaangle_ = nullptr;
  ::memset(&_impl_.playerid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.ultimateskill_) -
      reinterpret_cast<char*>(&_impl_.playerid_)) + sizeof(_impl_.ultimateskill_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BattleSyncRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 playerID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.playerid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 tick = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.tick_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .UnityMath.Vector2D moveDir = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_movedir(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool jump = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.jump_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float yaw = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          _impl_.yaw_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float pitch = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 53)) {
          _impl_.pitch_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // bool activeSkill = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.activeskill_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool ultimateSkill = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.ultimateskill_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .UnityMath.Vector3D position = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_position(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .UnityMath.Vector3D eulaAngle = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr = ctx->ParseMessage(_internal_mutable_eulaangle(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BattleSyncRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BattleSyncPackage.BattleSyncRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 playerID = 1;
  if (this->_internal_playerid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_playerid(), target);
  }

  // uint32 tick = 2;
  if (this->_internal_tick() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_tick(), target);
  }

  // .UnityMath.Vector2D moveDir = 3;
  if (this->_internal_has_movedir()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::movedir(this),
        _Internal::movedir(this).GetCachedSize(), target, stream);
  }

  // bool jump = 4;
  if (this->_internal_jump() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_jump(), target);
  }

  // float yaw = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_yaw = this->_internal_yaw();
  uint32_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(5, this->_internal_yaw(), target);
  }

  // float pitch = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pitch = this->_internal_pitch();
  uint32_t raw_pitch;
  memcpy(&raw_pitch, &tmp_pitch, sizeof(tmp_pitch));
  if (raw_pitch != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(6, this->_internal_pitch(), target);
  }

  // bool activeSkill = 7;
  if (this->_internal_activeskill() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(7, this->_internal_activeskill(), target);
  }

  // bool ultimateSkill = 8;
  if (this->_internal_ultimateskill() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(8, this->_internal_ultimateskill(), target);
  }

  // .UnityMath.Vector3D position = 9;
  if (this->_internal_has_position()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(9, _Internal::position(this),
        _Internal::position(this).GetCachedSize(), target, stream);
  }

  // .UnityMath.Vector3D eulaAngle = 10;
  if (this->_internal_has_eulaangle()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(10, _Internal::eulaangle(this),
        _Internal::eulaangle(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BattleSyncPackage.BattleSyncRequest)
  return target;
}

size_t BattleSyncRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BattleSyncPackage.BattleSyncRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .UnityMath.Vector2D moveDir = 3;
  if (this->_internal_has_movedir()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.movedir_);
  }

  // .UnityMath.Vector3D position = 9;
  if (this->_internal_has_position()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.position_);
  }

  // .UnityMath.Vector3D eulaAngle = 10;
  if (this->_internal_has_eulaangle()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.eulaangle_);
  }

  // uint32 playerID = 1;
  if (this->_internal_playerid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_playerid());
  }

  // uint32 tick = 2;
  if (this->_internal_tick() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_tick());
  }

  // float yaw = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_yaw = this->_internal_yaw();
  uint32_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    total_size += 1 + 4;
  }

  // float pitch = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pitch = this->_internal_pitch();
  uint32_t raw_pitch;
  memcpy(&raw_pitch, &tmp_pitch, sizeof(tmp_pitch));
  if (raw_pitch != 0) {
    total_size += 1 + 4;
  }

  // bool jump = 4;
  if (this->_internal_jump() != 0) {
    total_size += 1 + 1;
  }

  // bool activeSkill = 7;
  if (this->_internal_activeskill() != 0) {
    total_size += 1 + 1;
  }

  // bool ultimateSkill = 8;
  if (this->_internal_ultimateskill() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BattleSyncRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BattleSyncRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BattleSyncRequest::GetClassData() const { return &_class_data_; }


void BattleSyncRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BattleSyncRequest*>(&to_msg);
  auto& from = static_cast<const BattleSyncRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BattleSyncPackage.BattleSyncRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_movedir()) {
    _this->_internal_mutable_movedir()->::UnityMath::Vector2D::MergeFrom(
        from._internal_movedir());
  }
  if (from._internal_has_position()) {
    _this->_internal_mutable_position()->::UnityMath::Vector3D::MergeFrom(
        from._internal_position());
  }
  if (from._internal_has_eulaangle()) {
    _this->_internal_mutable_eulaangle()->::UnityMath::Vector3D::MergeFrom(
        from._internal_eulaangle());
  }
  if (from._internal_playerid() != 0) {
    _this->_internal_set_playerid(from._internal_playerid());
  }
  if (from._internal_tick() != 0) {
    _this->_internal_set_tick(from._internal_tick());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_yaw = from._internal_yaw();
  uint32_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    _this->_internal_set_yaw(from._internal_yaw());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pitch = from._internal_pitch();
  uint32_t raw_pitch;
  memcpy(&raw_pitch, &tmp_pitch, sizeof(tmp_pitch));
  if (raw_pitch != 0) {
    _this->_internal_set_pitch(from._internal_pitch());
  }
  if (from._internal_jump() != 0) {
    _this->_internal_set_jump(from._internal_jump());
  }
  if (from._internal_activeskill() != 0) {
    _this->_internal_set_activeskill(from._internal_activeskill());
  }
  if (from._internal_ultimateskill() != 0) {
    _this->_internal_set_ultimateskill(from._internal_ultimateskill());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BattleSyncRequest::CopyFrom(const BattleSyncRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BattleSyncPackage.BattleSyncRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BattleSyncRequest::IsInitialized() const {
  return true;
}

void BattleSyncRequest::InternalSwap(BattleSyncRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BattleSyncRequest, _impl_.ultimateskill_)
      + sizeof(BattleSyncRequest::_impl_.ultimateskill_)
      - PROTOBUF_FIELD_OFFSET(BattleSyncRequest, _impl_.movedir_)>(
          reinterpret_cast<char*>(&_impl_.movedir_),
          reinterpret_cast<char*>(&other->_impl_.movedir_));
}

::PROTOBUF_NAMESPACE_ID::Metadata BattleSyncRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_BattleSyncPackage_2eproto_getter, &descriptor_table_BattleSyncPackage_2eproto_once,
      file_level_metadata_BattleSyncPackage_2eproto[0]);
}

// ===================================================================

class BattleSyncResponse::_Internal {
 public:
};

BattleSyncResponse::BattleSyncResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:BattleSyncPackage.BattleSyncResponse)
}
BattleSyncResponse::BattleSyncResponse(const BattleSyncResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BattleSyncResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.states_){from._impl_.states_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:BattleSyncPackage.BattleSyncResponse)
}

inline void BattleSyncResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.states_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BattleSyncResponse::~BattleSyncResponse() {
  // @@protoc_insertion_point(destructor:BattleSyncPackage.BattleSyncResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BattleSyncResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.states_.~RepeatedPtrField();
}

void BattleSyncResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BattleSyncResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:BattleSyncPackage.BattleSyncResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.states_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BattleSyncResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .BattleSyncPackage.PlayerState states = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_states(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BattleSyncResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BattleSyncPackage.BattleSyncResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .BattleSyncPackage.PlayerState states = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_states_size()); i < n; i++) {
    const auto& repfield = this->_internal_states(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BattleSyncPackage.BattleSyncResponse)
  return target;
}

size_t BattleSyncResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BattleSyncPackage.BattleSyncResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .BattleSyncPackage.PlayerState states = 1;
  total_size += 1UL * this->_internal_states_size();
  for (const auto& msg : this->_impl_.states_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BattleSyncResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BattleSyncResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BattleSyncResponse::GetClassData() const { return &_class_data_; }


void BattleSyncResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BattleSyncResponse*>(&to_msg);
  auto& from = static_cast<const BattleSyncResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BattleSyncPackage.BattleSyncResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.states_.MergeFrom(from._impl_.states_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BattleSyncResponse::CopyFrom(const BattleSyncResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BattleSyncPackage.BattleSyncResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BattleSyncResponse::IsInitialized() const {
  return true;
}

void BattleSyncResponse::InternalSwap(BattleSyncResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.states_.InternalSwap(&other->_impl_.states_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BattleSyncResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_BattleSyncPackage_2eproto_getter, &descriptor_table_BattleSyncPackage_2eproto_once,
      file_level_metadata_BattleSyncPackage_2eproto[1]);
}

// ===================================================================

class PlayerState::_Internal {
 public:
  static const ::UnityMath::Vector2D& movedir(const PlayerState* msg);
  static const ::UnityMath::Vector3D& position(const PlayerState* msg);
  static const ::UnityMath::Vector3D& eulaangle(const PlayerState* msg);
};

const ::UnityMath::Vector2D&
PlayerState::_Internal::movedir(const PlayerState* msg) {
  return *msg->_impl_.movedir_;
}
const ::UnityMath::Vector3D&
PlayerState::_Internal::position(const PlayerState* msg) {
  return *msg->_impl_.position_;
}
const ::UnityMath::Vector3D&
PlayerState::_Internal::eulaangle(const PlayerState* msg) {
  return *msg->_impl_.eulaangle_;
}
void PlayerState::clear_movedir() {
  if (GetArenaForAllocation() == nullptr && _impl_.movedir_ != nullptr) {
    delete _impl_.movedir_;
  }
  _impl_.movedir_ = nullptr;
}
void PlayerState::clear_position() {
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
}
void PlayerState::clear_eulaangle() {
  if (GetArenaForAllocation() == nullptr && _impl_.eulaangle_ != nullptr) {
    delete _impl_.eulaangle_;
  }
  _impl_.eulaangle_ = nullptr;
}
PlayerState::PlayerState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:BattleSyncPackage.PlayerState)
}
PlayerState::PlayerState(const PlayerState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.movedir_){nullptr}
    , decltype(_impl_.position_){nullptr}
    , decltype(_impl_.eulaangle_){nullptr}
    , decltype(_impl_.playerid_){}
    , decltype(_impl_.tick_){}
    , decltype(_impl_.yaw_){}
    , decltype(_impl_.pitch_){}
    , decltype(_impl_.jump_){}
    , decltype(_impl_.activeskill_){}
    , decltype(_impl_.ultimateskill_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_movedir()) {
    _this->_impl_.movedir_ = new ::UnityMath::Vector2D(*from._impl_.movedir_);
  }
  if (from._internal_has_position()) {
    _this->_impl_.position_ = new ::UnityMath::Vector3D(*from._impl_.position_);
  }
  if (from._internal_has_eulaangle()) {
    _this->_impl_.eulaangle_ = new ::UnityMath::Vector3D(*from._impl_.eulaangle_);
  }
  ::memcpy(&_impl_.playerid_, &from._impl_.playerid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.ultimateskill_) -
    reinterpret_cast<char*>(&_impl_.playerid_)) + sizeof(_impl_.ultimateskill_));
  // @@protoc_insertion_point(copy_constructor:BattleSyncPackage.PlayerState)
}

inline void PlayerState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.movedir_){nullptr}
    , decltype(_impl_.position_){nullptr}
    , decltype(_impl_.eulaangle_){nullptr}
    , decltype(_impl_.playerid_){0u}
    , decltype(_impl_.tick_){0u}
    , decltype(_impl_.yaw_){0}
    , decltype(_impl_.pitch_){0}
    , decltype(_impl_.jump_){false}
    , decltype(_impl_.activeskill_){false}
    , decltype(_impl_.ultimateskill_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PlayerState::~PlayerState() {
  // @@protoc_insertion_point(destructor:BattleSyncPackage.PlayerState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.movedir_;
  if (this != internal_default_instance()) delete _impl_.position_;
  if (this != internal_default_instance()) delete _impl_.eulaangle_;
}

void PlayerState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerState::Clear() {
// @@protoc_insertion_point(message_clear_start:BattleSyncPackage.PlayerState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.movedir_ != nullptr) {
    delete _impl_.movedir_;
  }
  _impl_.movedir_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.eulaangle_ != nullptr) {
    delete _impl_.eulaangle_;
  }
  _impl_.eulaangle_ = nullptr;
  ::memset(&_impl_.playerid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.ultimateskill_) -
      reinterpret_cast<char*>(&_impl_.playerid_)) + sizeof(_impl_.ultimateskill_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 playerID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.playerid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 tick = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.tick_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .UnityMath.Vector2D moveDir = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_movedir(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool jump = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.jump_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float yaw = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          _impl_.yaw_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float pitch = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 53)) {
          _impl_.pitch_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // bool activeSkill = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.activeskill_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool ultimateSkill = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.ultimateskill_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .UnityMath.Vector3D position = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_position(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .UnityMath.Vector3D eulaAngle = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr = ctx->ParseMessage(_internal_mutable_eulaangle(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BattleSyncPackage.PlayerState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 playerID = 1;
  if (this->_internal_playerid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_playerid(), target);
  }

  // uint32 tick = 2;
  if (this->_internal_tick() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_tick(), target);
  }

  // .UnityMath.Vector2D moveDir = 3;
  if (this->_internal_has_movedir()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::movedir(this),
        _Internal::movedir(this).GetCachedSize(), target, stream);
  }

  // bool jump = 4;
  if (this->_internal_jump() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_jump(), target);
  }

  // float yaw = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_yaw = this->_internal_yaw();
  uint32_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(5, this->_internal_yaw(), target);
  }

  // float pitch = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pitch = this->_internal_pitch();
  uint32_t raw_pitch;
  memcpy(&raw_pitch, &tmp_pitch, sizeof(tmp_pitch));
  if (raw_pitch != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(6, this->_internal_pitch(), target);
  }

  // bool activeSkill = 7;
  if (this->_internal_activeskill() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(7, this->_internal_activeskill(), target);
  }

  // bool ultimateSkill = 8;
  if (this->_internal_ultimateskill() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(8, this->_internal_ultimateskill(), target);
  }

  // .UnityMath.Vector3D position = 9;
  if (this->_internal_has_position()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(9, _Internal::position(this),
        _Internal::position(this).GetCachedSize(), target, stream);
  }

  // .UnityMath.Vector3D eulaAngle = 10;
  if (this->_internal_has_eulaangle()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(10, _Internal::eulaangle(this),
        _Internal::eulaangle(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BattleSyncPackage.PlayerState)
  return target;
}

size_t PlayerState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BattleSyncPackage.PlayerState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .UnityMath.Vector2D moveDir = 3;
  if (this->_internal_has_movedir()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.movedir_);
  }

  // .UnityMath.Vector3D position = 9;
  if (this->_internal_has_position()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.position_);
  }

  // .UnityMath.Vector3D eulaAngle = 10;
  if (this->_internal_has_eulaangle()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.eulaangle_);
  }

  // uint32 playerID = 1;
  if (this->_internal_playerid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_playerid());
  }

  // uint32 tick = 2;
  if (this->_internal_tick() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_tick());
  }

  // float yaw = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_yaw = this->_internal_yaw();
  uint32_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    total_size += 1 + 4;
  }

  // float pitch = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pitch = this->_internal_pitch();
  uint32_t raw_pitch;
  memcpy(&raw_pitch, &tmp_pitch, sizeof(tmp_pitch));
  if (raw_pitch != 0) {
    total_size += 1 + 4;
  }

  // bool jump = 4;
  if (this->_internal_jump() != 0) {
    total_size += 1 + 1;
  }

  // bool activeSkill = 7;
  if (this->_internal_activeskill() != 0) {
    total_size += 1 + 1;
  }

  // bool ultimateSkill = 8;
  if (this->_internal_ultimateskill() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerState::GetClassData() const { return &_class_data_; }


void PlayerState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerState*>(&to_msg);
  auto& from = static_cast<const PlayerState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BattleSyncPackage.PlayerState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_movedir()) {
    _this->_internal_mutable_movedir()->::UnityMath::Vector2D::MergeFrom(
        from._internal_movedir());
  }
  if (from._internal_has_position()) {
    _this->_internal_mutable_position()->::UnityMath::Vector3D::MergeFrom(
        from._internal_position());
  }
  if (from._internal_has_eulaangle()) {
    _this->_internal_mutable_eulaangle()->::UnityMath::Vector3D::MergeFrom(
        from._internal_eulaangle());
  }
  if (from._internal_playerid() != 0) {
    _this->_internal_set_playerid(from._internal_playerid());
  }
  if (from._internal_tick() != 0) {
    _this->_internal_set_tick(from._internal_tick());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_yaw = from._internal_yaw();
  uint32_t raw_yaw;
  memcpy(&raw_yaw, &tmp_yaw, sizeof(tmp_yaw));
  if (raw_yaw != 0) {
    _this->_internal_set_yaw(from._internal_yaw());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_pitch = from._internal_pitch();
  uint32_t raw_pitch;
  memcpy(&raw_pitch, &tmp_pitch, sizeof(tmp_pitch));
  if (raw_pitch != 0) {
    _this->_internal_set_pitch(from._internal_pitch());
  }
  if (from._internal_jump() != 0) {
    _this->_internal_set_jump(from._internal_jump());
  }
  if (from._internal_activeskill() != 0) {
    _this->_internal_set_activeskill(from._internal_activeskill());
  }
  if (from._internal_ultimateskill() != 0) {
    _this->_internal_set_ultimateskill(from._internal_ultimateskill());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerState::CopyFrom(const PlayerState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BattleSyncPackage.PlayerState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerState::IsInitialized() const {
  return true;
}

void PlayerState::InternalSwap(PlayerState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerState, _impl_.ultimateskill_)
      + sizeof(PlayerState::_impl_.ultimateskill_)
      - PROTOBUF_FIELD_OFFSET(PlayerState, _impl_.movedir_)>(
          reinterpret_cast<char*>(&_impl_.movedir_),
          reinterpret_cast<char*>(&other->_impl_.movedir_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_BattleSyncPackage_2eproto_getter, &descriptor_table_BattleSyncPackage_2eproto_once,
      file_level_metadata_BattleSyncPackage_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace BattleSyncPackage
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::BattleSyncPackage::BattleSyncRequest*
Arena::CreateMaybeMessage< ::BattleSyncPackage::BattleSyncRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::BattleSyncPackage::BattleSyncRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::BattleSyncPackage::BattleSyncResponse*
Arena::CreateMaybeMessage< ::BattleSyncPackage::BattleSyncResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::BattleSyncPackage::BattleSyncResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::BattleSyncPackage::PlayerState*
Arena::CreateMaybeMessage< ::BattleSyncPackage::PlayerState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::BattleSyncPackage::PlayerState >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
