// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientSyncPackage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ClientSyncPackage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ClientSyncPackage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ClientSyncPackage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ClientSyncPackage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ClientSyncPackage_2eproto;
namespace ClientSyncPackage {
class ClientSyncRequest;
struct ClientSyncRequestDefaultTypeInternal;
extern ClientSyncRequestDefaultTypeInternal _ClientSyncRequest_default_instance_;
class ClientSyncResponse;
struct ClientSyncResponseDefaultTypeInternal;
extern ClientSyncResponseDefaultTypeInternal _ClientSyncResponse_default_instance_;
class ConnectRequestPackage;
struct ConnectRequestPackageDefaultTypeInternal;
extern ConnectRequestPackageDefaultTypeInternal _ConnectRequestPackage_default_instance_;
class ConnectResponsePackage;
struct ConnectResponsePackageDefaultTypeInternal;
extern ConnectResponsePackageDefaultTypeInternal _ConnectResponsePackage_default_instance_;
class HeartBeatPackage;
struct HeartBeatPackageDefaultTypeInternal;
extern HeartBeatPackageDefaultTypeInternal _HeartBeatPackage_default_instance_;
}  // namespace ClientSyncPackage
PROTOBUF_NAMESPACE_OPEN
template<> ::ClientSyncPackage::ClientSyncRequest* Arena::CreateMaybeMessage<::ClientSyncPackage::ClientSyncRequest>(Arena*);
template<> ::ClientSyncPackage::ClientSyncResponse* Arena::CreateMaybeMessage<::ClientSyncPackage::ClientSyncResponse>(Arena*);
template<> ::ClientSyncPackage::ConnectRequestPackage* Arena::CreateMaybeMessage<::ClientSyncPackage::ConnectRequestPackage>(Arena*);
template<> ::ClientSyncPackage::ConnectResponsePackage* Arena::CreateMaybeMessage<::ClientSyncPackage::ConnectResponsePackage>(Arena*);
template<> ::ClientSyncPackage::HeartBeatPackage* Arena::CreateMaybeMessage<::ClientSyncPackage::HeartBeatPackage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ClientSyncPackage {

enum LocalClientEvent : int {
  Local_ACK_None = 0,
  HeartBeat = 1,
  ConnectRequest = 2,
  DisconnectRequest = 3,
  LocalClientEvent_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  LocalClientEvent_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool LocalClientEvent_IsValid(int value);
constexpr LocalClientEvent LocalClientEvent_MIN = Local_ACK_None;
constexpr LocalClientEvent LocalClientEvent_MAX = DisconnectRequest;
constexpr int LocalClientEvent_ARRAYSIZE = LocalClientEvent_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LocalClientEvent_descriptor();
template<typename T>
inline const std::string& LocalClientEvent_Name(T enum_t_value) {
  static_assert(::std::is_same<T, LocalClientEvent>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function LocalClientEvent_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    LocalClientEvent_descriptor(), enum_t_value);
}
inline bool LocalClientEvent_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LocalClientEvent* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LocalClientEvent>(
    LocalClientEvent_descriptor(), name, value);
}
enum RemoteClientEvent : int {
  Remote_ACK_None = 0,
  ConnectResponse = 1,
  RemoteClientEvent_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  RemoteClientEvent_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool RemoteClientEvent_IsValid(int value);
constexpr RemoteClientEvent RemoteClientEvent_MIN = Remote_ACK_None;
constexpr RemoteClientEvent RemoteClientEvent_MAX = ConnectResponse;
constexpr int RemoteClientEvent_ARRAYSIZE = RemoteClientEvent_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RemoteClientEvent_descriptor();
template<typename T>
inline const std::string& RemoteClientEvent_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RemoteClientEvent>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RemoteClientEvent_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RemoteClientEvent_descriptor(), enum_t_value);
}
inline bool RemoteClientEvent_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RemoteClientEvent* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RemoteClientEvent>(
    RemoteClientEvent_descriptor(), name, value);
}
// ===================================================================

class ClientSyncRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ClientSyncPackage.ClientSyncRequest) */ {
 public:
  inline ClientSyncRequest() : ClientSyncRequest(nullptr) {}
  ~ClientSyncRequest() override;
  explicit PROTOBUF_CONSTEXPR ClientSyncRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientSyncRequest(const ClientSyncRequest& from);
  ClientSyncRequest(ClientSyncRequest&& from) noexcept
    : ClientSyncRequest() {
    *this = ::std::move(from);
  }

  inline ClientSyncRequest& operator=(const ClientSyncRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientSyncRequest& operator=(ClientSyncRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientSyncRequest& default_instance() {
    return *internal_default_instance();
  }
  enum ContentCase {
    kHeartBeat = 2,
    kConnect = 3,
    CONTENT_NOT_SET = 0,
  };

  static inline const ClientSyncRequest* internal_default_instance() {
    return reinterpret_cast<const ClientSyncRequest*>(
               &_ClientSyncRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClientSyncRequest& a, ClientSyncRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientSyncRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientSyncRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientSyncRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientSyncRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClientSyncRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ClientSyncRequest& from) {
    ClientSyncRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientSyncRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ClientSyncPackage.ClientSyncRequest";
  }
  protected:
  explicit ClientSyncRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEventIDFieldNumber = 1,
    kHeartBeatFieldNumber = 2,
    kConnectFieldNumber = 3,
  };
  // .ClientSyncPackage.LocalClientEvent eventID = 1;
  void clear_eventid();
  ::ClientSyncPackage::LocalClientEvent eventid() const;
  void set_eventid(::ClientSyncPackage::LocalClientEvent value);
  private:
  ::ClientSyncPackage::LocalClientEvent _internal_eventid() const;
  void _internal_set_eventid(::ClientSyncPackage::LocalClientEvent value);
  public:

  // .ClientSyncPackage.HeartBeatPackage heartBeat = 2;
  bool has_heartbeat() const;
  private:
  bool _internal_has_heartbeat() const;
  public:
  void clear_heartbeat();
  const ::ClientSyncPackage::HeartBeatPackage& heartbeat() const;
  PROTOBUF_NODISCARD ::ClientSyncPackage::HeartBeatPackage* release_heartbeat();
  ::ClientSyncPackage::HeartBeatPackage* mutable_heartbeat();
  void set_allocated_heartbeat(::ClientSyncPackage::HeartBeatPackage* heartbeat);
  private:
  const ::ClientSyncPackage::HeartBeatPackage& _internal_heartbeat() const;
  ::ClientSyncPackage::HeartBeatPackage* _internal_mutable_heartbeat();
  public:
  void unsafe_arena_set_allocated_heartbeat(
      ::ClientSyncPackage::HeartBeatPackage* heartbeat);
  ::ClientSyncPackage::HeartBeatPackage* unsafe_arena_release_heartbeat();

  // .ClientSyncPackage.ConnectRequestPackage connect = 3;
  bool has_connect() const;
  private:
  bool _internal_has_connect() const;
  public:
  void clear_connect();
  const ::ClientSyncPackage::ConnectRequestPackage& connect() const;
  PROTOBUF_NODISCARD ::ClientSyncPackage::ConnectRequestPackage* release_connect();
  ::ClientSyncPackage::ConnectRequestPackage* mutable_connect();
  void set_allocated_connect(::ClientSyncPackage::ConnectRequestPackage* connect);
  private:
  const ::ClientSyncPackage::ConnectRequestPackage& _internal_connect() const;
  ::ClientSyncPackage::ConnectRequestPackage* _internal_mutable_connect();
  public:
  void unsafe_arena_set_allocated_connect(
      ::ClientSyncPackage::ConnectRequestPackage* connect);
  ::ClientSyncPackage::ConnectRequestPackage* unsafe_arena_release_connect();

  void clear_content();
  ContentCase content_case() const;
  // @@protoc_insertion_point(class_scope:ClientSyncPackage.ClientSyncRequest)
 private:
  class _Internal;
  void set_has_heartbeat();
  void set_has_connect();

  inline bool has_content() const;
  inline void clear_has_content();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int eventid_;
    union ContentUnion {
      constexpr ContentUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::ClientSyncPackage::HeartBeatPackage* heartbeat_;
      ::ClientSyncPackage::ConnectRequestPackage* connect_;
    } content_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ClientSyncPackage_2eproto;
};
// -------------------------------------------------------------------

class HeartBeatPackage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ClientSyncPackage.HeartBeatPackage) */ {
 public:
  inline HeartBeatPackage() : HeartBeatPackage(nullptr) {}
  ~HeartBeatPackage() override;
  explicit PROTOBUF_CONSTEXPR HeartBeatPackage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HeartBeatPackage(const HeartBeatPackage& from);
  HeartBeatPackage(HeartBeatPackage&& from) noexcept
    : HeartBeatPackage() {
    *this = ::std::move(from);
  }

  inline HeartBeatPackage& operator=(const HeartBeatPackage& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeartBeatPackage& operator=(HeartBeatPackage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HeartBeatPackage& default_instance() {
    return *internal_default_instance();
  }
  static inline const HeartBeatPackage* internal_default_instance() {
    return reinterpret_cast<const HeartBeatPackage*>(
               &_HeartBeatPackage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(HeartBeatPackage& a, HeartBeatPackage& b) {
    a.Swap(&b);
  }
  inline void Swap(HeartBeatPackage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeartBeatPackage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HeartBeatPackage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HeartBeatPackage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HeartBeatPackage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HeartBeatPackage& from) {
    HeartBeatPackage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HeartBeatPackage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ClientSyncPackage.HeartBeatPackage";
  }
  protected:
  explicit HeartBeatPackage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientIDFieldNumber = 1,
  };
  // uint32 clientID = 1;
  void clear_clientid();
  uint32_t clientid() const;
  void set_clientid(uint32_t value);
  private:
  uint32_t _internal_clientid() const;
  void _internal_set_clientid(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ClientSyncPackage.HeartBeatPackage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t clientid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ClientSyncPackage_2eproto;
};
// -------------------------------------------------------------------

class ConnectRequestPackage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ClientSyncPackage.ConnectRequestPackage) */ {
 public:
  inline ConnectRequestPackage() : ConnectRequestPackage(nullptr) {}
  ~ConnectRequestPackage() override;
  explicit PROTOBUF_CONSTEXPR ConnectRequestPackage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ConnectRequestPackage(const ConnectRequestPackage& from);
  ConnectRequestPackage(ConnectRequestPackage&& from) noexcept
    : ConnectRequestPackage() {
    *this = ::std::move(from);
  }

  inline ConnectRequestPackage& operator=(const ConnectRequestPackage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConnectRequestPackage& operator=(ConnectRequestPackage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConnectRequestPackage& default_instance() {
    return *internal_default_instance();
  }
  static inline const ConnectRequestPackage* internal_default_instance() {
    return reinterpret_cast<const ConnectRequestPackage*>(
               &_ConnectRequestPackage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ConnectRequestPackage& a, ConnectRequestPackage& b) {
    a.Swap(&b);
  }
  inline void Swap(ConnectRequestPackage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConnectRequestPackage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConnectRequestPackage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ConnectRequestPackage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ConnectRequestPackage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ConnectRequestPackage& from) {
    ConnectRequestPackage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConnectRequestPackage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ClientSyncPackage.ConnectRequestPackage";
  }
  protected:
  explicit ConnectRequestPackage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPortFieldNumber = 1,
  };
  // int32 port = 1;
  void clear_port();
  int32_t port() const;
  void set_port(int32_t value);
  private:
  int32_t _internal_port() const;
  void _internal_set_port(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ClientSyncPackage.ConnectRequestPackage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t port_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ClientSyncPackage_2eproto;
};
// -------------------------------------------------------------------

class ClientSyncResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ClientSyncPackage.ClientSyncResponse) */ {
 public:
  inline ClientSyncResponse() : ClientSyncResponse(nullptr) {}
  ~ClientSyncResponse() override;
  explicit PROTOBUF_CONSTEXPR ClientSyncResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientSyncResponse(const ClientSyncResponse& from);
  ClientSyncResponse(ClientSyncResponse&& from) noexcept
    : ClientSyncResponse() {
    *this = ::std::move(from);
  }

  inline ClientSyncResponse& operator=(const ClientSyncResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientSyncResponse& operator=(ClientSyncResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientSyncResponse& default_instance() {
    return *internal_default_instance();
  }
  enum ContentCase {
    kConnectResponse = 2,
    CONTENT_NOT_SET = 0,
  };

  static inline const ClientSyncResponse* internal_default_instance() {
    return reinterpret_cast<const ClientSyncResponse*>(
               &_ClientSyncResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ClientSyncResponse& a, ClientSyncResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientSyncResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientSyncResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientSyncResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientSyncResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClientSyncResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ClientSyncResponse& from) {
    ClientSyncResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientSyncResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ClientSyncPackage.ClientSyncResponse";
  }
  protected:
  explicit ClientSyncResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEventIDFieldNumber = 1,
    kConnectResponseFieldNumber = 2,
  };
  // .ClientSyncPackage.RemoteClientEvent eventID = 1;
  void clear_eventid();
  ::ClientSyncPackage::RemoteClientEvent eventid() const;
  void set_eventid(::ClientSyncPackage::RemoteClientEvent value);
  private:
  ::ClientSyncPackage::RemoteClientEvent _internal_eventid() const;
  void _internal_set_eventid(::ClientSyncPackage::RemoteClientEvent value);
  public:

  // .ClientSyncPackage.ConnectResponsePackage connectResponse = 2;
  bool has_connectresponse() const;
  private:
  bool _internal_has_connectresponse() const;
  public:
  void clear_connectresponse();
  const ::ClientSyncPackage::ConnectResponsePackage& connectresponse() const;
  PROTOBUF_NODISCARD ::ClientSyncPackage::ConnectResponsePackage* release_connectresponse();
  ::ClientSyncPackage::ConnectResponsePackage* mutable_connectresponse();
  void set_allocated_connectresponse(::ClientSyncPackage::ConnectResponsePackage* connectresponse);
  private:
  const ::ClientSyncPackage::ConnectResponsePackage& _internal_connectresponse() const;
  ::ClientSyncPackage::ConnectResponsePackage* _internal_mutable_connectresponse();
  public:
  void unsafe_arena_set_allocated_connectresponse(
      ::ClientSyncPackage::ConnectResponsePackage* connectresponse);
  ::ClientSyncPackage::ConnectResponsePackage* unsafe_arena_release_connectresponse();

  void clear_content();
  ContentCase content_case() const;
  // @@protoc_insertion_point(class_scope:ClientSyncPackage.ClientSyncResponse)
 private:
  class _Internal;
  void set_has_connectresponse();

  inline bool has_content() const;
  inline void clear_has_content();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int eventid_;
    union ContentUnion {
      constexpr ContentUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::ClientSyncPackage::ConnectResponsePackage* connectresponse_;
    } content_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ClientSyncPackage_2eproto;
};
// -------------------------------------------------------------------

class ConnectResponsePackage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ClientSyncPackage.ConnectResponsePackage) */ {
 public:
  inline ConnectResponsePackage() : ConnectResponsePackage(nullptr) {}
  ~ConnectResponsePackage() override;
  explicit PROTOBUF_CONSTEXPR ConnectResponsePackage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ConnectResponsePackage(const ConnectResponsePackage& from);
  ConnectResponsePackage(ConnectResponsePackage&& from) noexcept
    : ConnectResponsePackage() {
    *this = ::std::move(from);
  }

  inline ConnectResponsePackage& operator=(const ConnectResponsePackage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConnectResponsePackage& operator=(ConnectResponsePackage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConnectResponsePackage& default_instance() {
    return *internal_default_instance();
  }
  static inline const ConnectResponsePackage* internal_default_instance() {
    return reinterpret_cast<const ConnectResponsePackage*>(
               &_ConnectResponsePackage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ConnectResponsePackage& a, ConnectResponsePackage& b) {
    a.Swap(&b);
  }
  inline void Swap(ConnectResponsePackage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConnectResponsePackage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConnectResponsePackage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ConnectResponsePackage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ConnectResponsePackage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ConnectResponsePackage& from) {
    ConnectResponsePackage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConnectResponsePackage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ClientSyncPackage.ConnectResponsePackage";
  }
  protected:
  explicit ConnectResponsePackage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 1,
  };
  // string content = 1;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // @@protoc_insertion_point(class_scope:ClientSyncPackage.ConnectResponsePackage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ClientSyncPackage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClientSyncRequest

// .ClientSyncPackage.LocalClientEvent eventID = 1;
inline void ClientSyncRequest::clear_eventid() {
  _impl_.eventid_ = 0;
}
inline ::ClientSyncPackage::LocalClientEvent ClientSyncRequest::_internal_eventid() const {
  return static_cast< ::ClientSyncPackage::LocalClientEvent >(_impl_.eventid_);
}
inline ::ClientSyncPackage::LocalClientEvent ClientSyncRequest::eventid() const {
  // @@protoc_insertion_point(field_get:ClientSyncPackage.ClientSyncRequest.eventID)
  return _internal_eventid();
}
inline void ClientSyncRequest::_internal_set_eventid(::ClientSyncPackage::LocalClientEvent value) {
  
  _impl_.eventid_ = value;
}
inline void ClientSyncRequest::set_eventid(::ClientSyncPackage::LocalClientEvent value) {
  _internal_set_eventid(value);
  // @@protoc_insertion_point(field_set:ClientSyncPackage.ClientSyncRequest.eventID)
}

// .ClientSyncPackage.HeartBeatPackage heartBeat = 2;
inline bool ClientSyncRequest::_internal_has_heartbeat() const {
  return content_case() == kHeartBeat;
}
inline bool ClientSyncRequest::has_heartbeat() const {
  return _internal_has_heartbeat();
}
inline void ClientSyncRequest::set_has_heartbeat() {
  _impl_._oneof_case_[0] = kHeartBeat;
}
inline void ClientSyncRequest::clear_heartbeat() {
  if (_internal_has_heartbeat()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.heartbeat_;
    }
    clear_has_content();
  }
}
inline ::ClientSyncPackage::HeartBeatPackage* ClientSyncRequest::release_heartbeat() {
  // @@protoc_insertion_point(field_release:ClientSyncPackage.ClientSyncRequest.heartBeat)
  if (_internal_has_heartbeat()) {
    clear_has_content();
    ::ClientSyncPackage::HeartBeatPackage* temp = _impl_.content_.heartbeat_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::ClientSyncPackage::HeartBeatPackage& ClientSyncRequest::_internal_heartbeat() const {
  return _internal_has_heartbeat()
      ? *_impl_.content_.heartbeat_
      : reinterpret_cast< ::ClientSyncPackage::HeartBeatPackage&>(::ClientSyncPackage::_HeartBeatPackage_default_instance_);
}
inline const ::ClientSyncPackage::HeartBeatPackage& ClientSyncRequest::heartbeat() const {
  // @@protoc_insertion_point(field_get:ClientSyncPackage.ClientSyncRequest.heartBeat)
  return _internal_heartbeat();
}
inline ::ClientSyncPackage::HeartBeatPackage* ClientSyncRequest::unsafe_arena_release_heartbeat() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ClientSyncPackage.ClientSyncRequest.heartBeat)
  if (_internal_has_heartbeat()) {
    clear_has_content();
    ::ClientSyncPackage::HeartBeatPackage* temp = _impl_.content_.heartbeat_;
    _impl_.content_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ClientSyncRequest::unsafe_arena_set_allocated_heartbeat(::ClientSyncPackage::HeartBeatPackage* heartbeat) {
  clear_content();
  if (heartbeat) {
    set_has_heartbeat();
    _impl_.content_.heartbeat_ = heartbeat;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ClientSyncPackage.ClientSyncRequest.heartBeat)
}
inline ::ClientSyncPackage::HeartBeatPackage* ClientSyncRequest::_internal_mutable_heartbeat() {
  if (!_internal_has_heartbeat()) {
    clear_content();
    set_has_heartbeat();
    _impl_.content_.heartbeat_ = CreateMaybeMessage< ::ClientSyncPackage::HeartBeatPackage >(GetArenaForAllocation());
  }
  return _impl_.content_.heartbeat_;
}
inline ::ClientSyncPackage::HeartBeatPackage* ClientSyncRequest::mutable_heartbeat() {
  ::ClientSyncPackage::HeartBeatPackage* _msg = _internal_mutable_heartbeat();
  // @@protoc_insertion_point(field_mutable:ClientSyncPackage.ClientSyncRequest.heartBeat)
  return _msg;
}

// .ClientSyncPackage.ConnectRequestPackage connect = 3;
inline bool ClientSyncRequest::_internal_has_connect() const {
  return content_case() == kConnect;
}
inline bool ClientSyncRequest::has_connect() const {
  return _internal_has_connect();
}
inline void ClientSyncRequest::set_has_connect() {
  _impl_._oneof_case_[0] = kConnect;
}
inline void ClientSyncRequest::clear_connect() {
  if (_internal_has_connect()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.connect_;
    }
    clear_has_content();
  }
}
inline ::ClientSyncPackage::ConnectRequestPackage* ClientSyncRequest::release_connect() {
  // @@protoc_insertion_point(field_release:ClientSyncPackage.ClientSyncRequest.connect)
  if (_internal_has_connect()) {
    clear_has_content();
    ::ClientSyncPackage::ConnectRequestPackage* temp = _impl_.content_.connect_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.connect_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::ClientSyncPackage::ConnectRequestPackage& ClientSyncRequest::_internal_connect() const {
  return _internal_has_connect()
      ? *_impl_.content_.connect_
      : reinterpret_cast< ::ClientSyncPackage::ConnectRequestPackage&>(::ClientSyncPackage::_ConnectRequestPackage_default_instance_);
}
inline const ::ClientSyncPackage::ConnectRequestPackage& ClientSyncRequest::connect() const {
  // @@protoc_insertion_point(field_get:ClientSyncPackage.ClientSyncRequest.connect)
  return _internal_connect();
}
inline ::ClientSyncPackage::ConnectRequestPackage* ClientSyncRequest::unsafe_arena_release_connect() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ClientSyncPackage.ClientSyncRequest.connect)
  if (_internal_has_connect()) {
    clear_has_content();
    ::ClientSyncPackage::ConnectRequestPackage* temp = _impl_.content_.connect_;
    _impl_.content_.connect_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ClientSyncRequest::unsafe_arena_set_allocated_connect(::ClientSyncPackage::ConnectRequestPackage* connect) {
  clear_content();
  if (connect) {
    set_has_connect();
    _impl_.content_.connect_ = connect;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ClientSyncPackage.ClientSyncRequest.connect)
}
inline ::ClientSyncPackage::ConnectRequestPackage* ClientSyncRequest::_internal_mutable_connect() {
  if (!_internal_has_connect()) {
    clear_content();
    set_has_connect();
    _impl_.content_.connect_ = CreateMaybeMessage< ::ClientSyncPackage::ConnectRequestPackage >(GetArenaForAllocation());
  }
  return _impl_.content_.connect_;
}
inline ::ClientSyncPackage::ConnectRequestPackage* ClientSyncRequest::mutable_connect() {
  ::ClientSyncPackage::ConnectRequestPackage* _msg = _internal_mutable_connect();
  // @@protoc_insertion_point(field_mutable:ClientSyncPackage.ClientSyncRequest.connect)
  return _msg;
}

inline bool ClientSyncRequest::has_content() const {
  return content_case() != CONTENT_NOT_SET;
}
inline void ClientSyncRequest::clear_has_content() {
  _impl_._oneof_case_[0] = CONTENT_NOT_SET;
}
inline ClientSyncRequest::ContentCase ClientSyncRequest::content_case() const {
  return ClientSyncRequest::ContentCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// HeartBeatPackage

// uint32 clientID = 1;
inline void HeartBeatPackage::clear_clientid() {
  _impl_.clientid_ = 0u;
}
inline uint32_t HeartBeatPackage::_internal_clientid() const {
  return _impl_.clientid_;
}
inline uint32_t HeartBeatPackage::clientid() const {
  // @@protoc_insertion_point(field_get:ClientSyncPackage.HeartBeatPackage.clientID)
  return _internal_clientid();
}
inline void HeartBeatPackage::_internal_set_clientid(uint32_t value) {
  
  _impl_.clientid_ = value;
}
inline void HeartBeatPackage::set_clientid(uint32_t value) {
  _internal_set_clientid(value);
  // @@protoc_insertion_point(field_set:ClientSyncPackage.HeartBeatPackage.clientID)
}

// -------------------------------------------------------------------

// ConnectRequestPackage

// int32 port = 1;
inline void ConnectRequestPackage::clear_port() {
  _impl_.port_ = 0;
}
inline int32_t ConnectRequestPackage::_internal_port() const {
  return _impl_.port_;
}
inline int32_t ConnectRequestPackage::port() const {
  // @@protoc_insertion_point(field_get:ClientSyncPackage.ConnectRequestPackage.port)
  return _internal_port();
}
inline void ConnectRequestPackage::_internal_set_port(int32_t value) {
  
  _impl_.port_ = value;
}
inline void ConnectRequestPackage::set_port(int32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:ClientSyncPackage.ConnectRequestPackage.port)
}

// -------------------------------------------------------------------

// ClientSyncResponse

// .ClientSyncPackage.RemoteClientEvent eventID = 1;
inline void ClientSyncResponse::clear_eventid() {
  _impl_.eventid_ = 0;
}
inline ::ClientSyncPackage::RemoteClientEvent ClientSyncResponse::_internal_eventid() const {
  return static_cast< ::ClientSyncPackage::RemoteClientEvent >(_impl_.eventid_);
}
inline ::ClientSyncPackage::RemoteClientEvent ClientSyncResponse::eventid() const {
  // @@protoc_insertion_point(field_get:ClientSyncPackage.ClientSyncResponse.eventID)
  return _internal_eventid();
}
inline void ClientSyncResponse::_internal_set_eventid(::ClientSyncPackage::RemoteClientEvent value) {
  
  _impl_.eventid_ = value;
}
inline void ClientSyncResponse::set_eventid(::ClientSyncPackage::RemoteClientEvent value) {
  _internal_set_eventid(value);
  // @@protoc_insertion_point(field_set:ClientSyncPackage.ClientSyncResponse.eventID)
}

// .ClientSyncPackage.ConnectResponsePackage connectResponse = 2;
inline bool ClientSyncResponse::_internal_has_connectresponse() const {
  return content_case() == kConnectResponse;
}
inline bool ClientSyncResponse::has_connectresponse() const {
  return _internal_has_connectresponse();
}
inline void ClientSyncResponse::set_has_connectresponse() {
  _impl_._oneof_case_[0] = kConnectResponse;
}
inline void ClientSyncResponse::clear_connectresponse() {
  if (_internal_has_connectresponse()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.content_.connectresponse_;
    }
    clear_has_content();
  }
}
inline ::ClientSyncPackage::ConnectResponsePackage* ClientSyncResponse::release_connectresponse() {
  // @@protoc_insertion_point(field_release:ClientSyncPackage.ClientSyncResponse.connectResponse)
  if (_internal_has_connectresponse()) {
    clear_has_content();
    ::ClientSyncPackage::ConnectResponsePackage* temp = _impl_.content_.connectresponse_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.content_.connectresponse_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::ClientSyncPackage::ConnectResponsePackage& ClientSyncResponse::_internal_connectresponse() const {
  return _internal_has_connectresponse()
      ? *_impl_.content_.connectresponse_
      : reinterpret_cast< ::ClientSyncPackage::ConnectResponsePackage&>(::ClientSyncPackage::_ConnectResponsePackage_default_instance_);
}
inline const ::ClientSyncPackage::ConnectResponsePackage& ClientSyncResponse::connectresponse() const {
  // @@protoc_insertion_point(field_get:ClientSyncPackage.ClientSyncResponse.connectResponse)
  return _internal_connectresponse();
}
inline ::ClientSyncPackage::ConnectResponsePackage* ClientSyncResponse::unsafe_arena_release_connectresponse() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ClientSyncPackage.ClientSyncResponse.connectResponse)
  if (_internal_has_connectresponse()) {
    clear_has_content();
    ::ClientSyncPackage::ConnectResponsePackage* temp = _impl_.content_.connectresponse_;
    _impl_.content_.connectresponse_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ClientSyncResponse::unsafe_arena_set_allocated_connectresponse(::ClientSyncPackage::ConnectResponsePackage* connectresponse) {
  clear_content();
  if (connectresponse) {
    set_has_connectresponse();
    _impl_.content_.connectresponse_ = connectresponse;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ClientSyncPackage.ClientSyncResponse.connectResponse)
}
inline ::ClientSyncPackage::ConnectResponsePackage* ClientSyncResponse::_internal_mutable_connectresponse() {
  if (!_internal_has_connectresponse()) {
    clear_content();
    set_has_connectresponse();
    _impl_.content_.connectresponse_ = CreateMaybeMessage< ::ClientSyncPackage::ConnectResponsePackage >(GetArenaForAllocation());
  }
  return _impl_.content_.connectresponse_;
}
inline ::ClientSyncPackage::ConnectResponsePackage* ClientSyncResponse::mutable_connectresponse() {
  ::ClientSyncPackage::ConnectResponsePackage* _msg = _internal_mutable_connectresponse();
  // @@protoc_insertion_point(field_mutable:ClientSyncPackage.ClientSyncResponse.connectResponse)
  return _msg;
}

inline bool ClientSyncResponse::has_content() const {
  return content_case() != CONTENT_NOT_SET;
}
inline void ClientSyncResponse::clear_has_content() {
  _impl_._oneof_case_[0] = CONTENT_NOT_SET;
}
inline ClientSyncResponse::ContentCase ClientSyncResponse::content_case() const {
  return ClientSyncResponse::ContentCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// ConnectResponsePackage

// string content = 1;
inline void ConnectResponsePackage::clear_content() {
  _impl_.content_.ClearToEmpty();
}
inline const std::string& ConnectResponsePackage::content() const {
  // @@protoc_insertion_point(field_get:ClientSyncPackage.ConnectResponsePackage.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ConnectResponsePackage::set_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.content_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ClientSyncPackage.ConnectResponsePackage.content)
}
inline std::string* ConnectResponsePackage::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:ClientSyncPackage.ConnectResponsePackage.content)
  return _s;
}
inline const std::string& ConnectResponsePackage::_internal_content() const {
  return _impl_.content_.Get();
}
inline void ConnectResponsePackage::_internal_set_content(const std::string& value) {
  
  _impl_.content_.Set(value, GetArenaForAllocation());
}
inline std::string* ConnectResponsePackage::_internal_mutable_content() {
  
  return _impl_.content_.Mutable(GetArenaForAllocation());
}
inline std::string* ConnectResponsePackage::release_content() {
  // @@protoc_insertion_point(field_release:ClientSyncPackage.ConnectResponsePackage.content)
  return _impl_.content_.Release();
}
inline void ConnectResponsePackage::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  _impl_.content_.SetAllocated(content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ClientSyncPackage.ConnectResponsePackage.content)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ClientSyncPackage

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ClientSyncPackage::LocalClientEvent> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ClientSyncPackage::LocalClientEvent>() {
  return ::ClientSyncPackage::LocalClientEvent_descriptor();
}
template <> struct is_proto_enum< ::ClientSyncPackage::RemoteClientEvent> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ClientSyncPackage::RemoteClientEvent>() {
  return ::ClientSyncPackage::RemoteClientEvent_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ClientSyncPackage_2eproto
