syntax = "proto3";

package AckPackage;

/* --------------------------------------------------
  确认同步包汇总
-------------------------------------------------- */
enum AckSyncEvent {
  HeartBeat = 0;
  Connect = 1;
  Disconnect = 2;
}

message AckSyncRequest {
  AckSyncEvent eventID = 1;
  oneof content {
    HeartBeatPackage heartBeat = 2;
    ConnectPackage connect = 3;
    DisconnectPackage disconnect = 4;
  }
}

/* --------------------------------------------------
  心跳包
-------------------------------------------------- */
message HeartBeatPackage {
  uint32 clientID = 1;
}

/* --------------------------------------------------
  连接请求包
-------------------------------------------------- */
message ConnectPackage {
   int32 port = 1;
}

message DisconnectPackage {
  int32 port = 1;
}