syntax = "proto3";

package AckSyncPackage;

/* ==================================================
  确认同步请求包事件
================================================== */
enum LocalAckEvent {
  Local_ACK_None = 0;
  HeartBeat = 1;
  ConnectRequest = 2;
  DisconnectRequest = 3;
}

// ===== ACK请求包 =====
message AckSyncRequest {
  LocalAckEvent eventID = 1;
  oneof content {
    HeartBeatPackage heartBeat = 2;
    ConnectRequestPackage connect = 3;
  }
}

// ===== 事件包 =====
message HeartBeatPackage {
  uint32 clientID = 1;
}

// ===== 连接请求包 =====
message ConnectRequestPackage {
  int32 port = 1;
}

/* ==================================================
  确认同步回应包事件
================================================== */
enum RemoteAckEvent {
  Remote_ACK_None = 0;
  ConnectResponse = 1;
}

// ===== ACK回应包 =====
message AckSyncResponse {
  RemoteAckEvent eventID = 1;
  oneof content {
    ConnectResponsePackage connectResponse = 2;
  }
}

// ===== 连接回应包 =====
message ConnectResponsePackage {
  string content = 1;
}




