syntax = "proto3";

package BattleSyncPackage;

import "UnityMath.proto";

/* ==================================================
  顶层封装-战局同步包
================================================== */
// ===== 本地战局同步请求包 =====
message BattleSyncRequest {
  uint32 playerID = 1;
  uint32 roomID = 2;
  uint32 tick = 3;

  // 玩家输入
  UnityMath.Vector2D moveDir = 4;
  bool jump = 5;
  float yaw = 6;
  float pitch = 7;
  bool activeSkill = 8;
  bool ultimateSkill = 9;

  // 测试使用，服务器暂未做世界模拟，客户端直接传输状态信息用于同步
  UnityMath.Vector3D position = 10;
  UnityMath.Vector3D eulaAngle = 11;
}

/* ==================================================
  顶层封装-战局同步包
================================================== */
// ===== 远程战局同步回应包 ======
message BattleSyncResponse {
  repeated PlayerState states = 1;
}

// ===== 服务器返回玩家状态 =====
message PlayerState {
  uint32 playerID = 1;
  uint32 roomID = 2;
  uint32 tick = 3;

  // 玩家输入
  UnityMath.Vector2D moveDir = 4;
  bool jump = 5;
  float yaw = 6;
  float pitch = 7;
  bool activeSkill = 8;
  bool ultimateSkill = 9;

  // 权威状态同步
  UnityMath.Vector3D position = 10;
  UnityMath.Vector3D eulaAngle = 11;
}
