syntax = "proto3";

package BattleSyncPackage;

import "UnityMath.proto";

/* --------------------------------------------------
  顶层封装-战局同步包
-------------------------------------------------- */
message BattleSync {
  uint32 eventID = 1; // 事件ID
}

/* --------------------------------------------------
  玩家输入抽象
-------------------------------------------------- */ 
message PlayerConfirmedInput {
  UnityMath.Vector2D moveDir = 1;
  bool jump = 2;
  float yaw = 3;
  float pitch = 4;
}

/* --------------------------------------------------
  同步事件
-------------------------------------------------- */
// 玩家输入同步
message PlayerInputCommand {
  uint32 playerID = 1;
  uint32 tick = 2;
  
  PlayerConfirmedInput input = 3;
}

// 服务器返回玩家状态
message PlayerState {
  uint32 playerID = 1;
  uint32 tick = 2;

  PlayerConfirmedInput input = 3;
  
  // 权威状态同步
  UnityMath.Vector3D position = 4;
  UnityMath.Vector3D eulaAngle = 5;
}