syntax = "proto3";

package LobbySyncPackage;

/* ==================================================
  顶层封装-大厅操作请求事件
================================================== */
enum LocalLobbyEvent {
  Local_Lobby_None = 0;
}

// ===== 大厅操作请求包 =====
message LobbySyncRequest {
  LocalLobbyEvent eventID = 1;
}

/* ==================================================
  顶层封装-大厅操作回应事件
================================================== */
enum RemoteLobbyEvent {
  Remote_Lobby_None = 0;
}

// ===== 大厅操作回应包 =====
message LobbySyncResponse {
  RemoteLobbyEvent eventID = 1;
}

