syntax = "proto3";

package LobbySyncPackage;

/* ==================================================
  顶层封装-大厅操作请求事件
================================================== */
enum LocalLobbyEvent {
  Local_Lobby_None = 0;
  Local_Lobby_Refresh = 1;
  Local_Lobby_RoomInfo = 2;
  Local_Lobby_RoomCreate = 3;
  Local_Lobby_RoomJoin = 4;
  Local_Lobby_RoomExit = 5;
}

// ===== 大厅操作请求包 =====
message LobbySyncRequest {
  LocalLobbyEvent eventID = 1;
  oneof content {
    RoomCreateRequest roomCreate = 2;
    RoomInfoRequest roomInfo = 3;
    RoomJoinRequest roomJoin = 4;
    RoomExitRequest roomExit = 5;
  }
}

// ===== 创建房间请求包 =====
message RoomCreateRequest {
  string roomName = 1;//房间名
  string roomType = 2;//房间类型
  string roomIntroduction = 3;//房间简介
}

// ===== 房间信息请求包 =====
message RoomInfoRequest {
  uint32 roomId = 1;
}

// ===== 加入房间请求包 =====
message RoomJoinRequest {
  uint32 roomId = 1;
}

// ===== 退出房间请求包 =====
message RoomExitRequest {
  uint32 roomId = 1;
}

/* ==================================================
  顶层封装-大厅操作回应事件
================================================== */
enum RemoteLobbyEvent {
  Remote_Lobby_None = 0;
  Remote_Lobby_Refresh = 1;
  Remote_Lobby_RoomInfo = 2;
  Remote_Lobby_RoomCreate = 3;
  Remote_Lobby_RoomJoin = 4;
  Remote_Lobby_RoomUpdate = 5;
  Remote_Lobby_RoomExit = 6;
}

// ===== 大厅操作回应包 =====
message LobbySyncResponse {
  RemoteLobbyEvent eventID = 1;
  oneof content{
    RefreshListResponsePackage refreshListResponse = 2;
    RoomCreateResponsePackage roomCreateResponse = 3;
    RoomInfoResponsePackage roomInfoResponse = 4;
    RoomJoinResponsePackage roomJoinResponse = 5;
    RoomExitResponsePackage roomExitResponse = 6;
  }
}

// ===== 大厅列表回应包 =====
message RefreshListResponsePackage{
  repeated RefreshResponsePackage rooms= 1;
}

// ===== 大厅列表回应子包 =====
message RefreshResponsePackage{
  uint32 roomId = 1;//房间id
  string roomName = 2;//房间名
  string roomType = 3;//类型
  string owner = 4;//房主名
  int32 max = 5;//人数上限
  int32 num = 6;//人数
}

// ===== 创建房间回应包 =====  这个暂时弃用
message RoomCreateResponsePackage {
  uint32 roomId = 1;
  uint32 max = 2;
  uint32 num = 3;
}

// ===== 房间信息回应包 =====
message RoomInfoResponsePackage {
  uint32 roomId = 1;
  string roomIntroduction = 2;//房间简介
  repeated string teamAPlayers = 3;
  repeated string teamBPlayers = 4;
}

// ===== 加入房间回应包 =====
message RoomJoinResponsePackage {
  uint32 roomId = 1;
  string roomName = 2;//房间名
  string roomType = 3;//房间类型
  string roomIntroduction = 4;//房间简介
  uint32 roomTeam = 5;//队伍 方便多队伍 1=A队 2=B队
  repeated string teamAPlayers = 6;
  repeated string teamBPlayers = 7;
}

// ===== 房间退出回应包 =====
message RoomExitResponsePackage{
  uint32 roomId = 1;
}