// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SyncPackage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SyncPackage {

  /// <summary>Holder for reflection information generated from SyncPackage.proto</summary>
  public static partial class SyncPackageReflection {

    #region Descriptor
    /// <summary>File descriptor for SyncPackage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SyncPackageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFTeW5jUGFja2FnZS5wcm90bxILU3luY1BhY2thZ2UaFkxvYmJ5U3luY1Bh",
            "Y2thZ2UucHJvdG8aF0NsaWVudFN5bmNQYWNrYWdlLnByb3RvIsABChBMb2Nh",
            "bFN5bmNQYWNrYWdlEiwKB2V2ZW50SUQYASABKA4yGy5TeW5jUGFja2FnZS5M",
            "b2NhbFN5bmNFdmVudBI3Cglsb2JieVN5bmMYAiABKAsyIi5Mb2JieVN5bmNQ",
            "YWNrYWdlLkxvYmJ5U3luY1JlcXVlc3RIABI6CgpjbGllbnRTeW5jGAMgASgL",
            "MiQuQ2xpZW50U3luY1BhY2thZ2UuQ2xpZW50U3luY1JlcXVlc3RIAEIJCgdj",
            "b250ZW50IsoBChFSZW1vdGVTeW5jUGFja2FnZRItCgdldmVudElEGAEgASgO",
            "MhwuU3luY1BhY2thZ2UuUmVtb3RlU3luY0V2ZW50EjsKDGxvYmJ5UGFja2Fn",
            "ZRgCIAEoCzIjLkxvYmJ5U3luY1BhY2thZ2UuTG9iYnlTeW5jUmVzcG9uc2VI",
            "ABI+Cg1jbGllbnRQYWNrYWdlGAMgASgLMiUuQ2xpZW50U3luY1BhY2thZ2Uu",
            "Q2xpZW50U3luY1Jlc3BvbnNlSABCCQoHY29udGVudCpFCg5Mb2NhbFN5bmNF",
            "dmVudBIOCgpMb2NhbF9Ob25lEAASEAoMTG9iYnlSZXF1ZXN0EAESEQoNQ2xp",
            "ZW50UmVxdWVzdBACKkkKD1JlbW90ZVN5bmNFdmVudBIPCgtSZW1vdGVfTm9u",
            "ZRAAEhEKDUxvYmJ5UmVzcG9uc2UQARISCg5DbGllbnRSZXNwb25zZRACYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::LobbySyncPackage.LobbySyncPackageReflection.Descriptor, global::ClientSyncPackage.ClientSyncPackageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SyncPackage.LocalSyncEvent), typeof(global::SyncPackage.RemoteSyncEvent), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SyncPackage.LocalSyncPackage), global::SyncPackage.LocalSyncPackage.Parser, new[]{ "EventID", "LobbySync", "ClientSync" }, new[]{ "Content" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SyncPackage.RemoteSyncPackage), global::SyncPackage.RemoteSyncPackage.Parser, new[]{ "EventID", "LobbyPackage", "ClientPackage" }, new[]{ "Content" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// ==================================================
  ///客户端->服务端同步包汇总
  ///================================================== 
  /// </summary>
  public enum LocalSyncEvent {
    [pbr::OriginalName("Local_None")] LocalNone = 0,
    [pbr::OriginalName("LobbyRequest")] LobbyRequest = 1,
    [pbr::OriginalName("ClientRequest")] ClientRequest = 2,
  }

  /// <summary>
  /// ==================================================
  ///服务端->客户端同步包汇总
  ///================================================== 
  /// </summary>
  public enum RemoteSyncEvent {
    [pbr::OriginalName("Remote_None")] RemoteNone = 0,
    [pbr::OriginalName("LobbyResponse")] LobbyResponse = 1,
    [pbr::OriginalName("ClientResponse")] ClientResponse = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 客户端发送给服务器的同步包
  /// </summary>
  public sealed partial class LocalSyncPackage : pb::IMessage<LocalSyncPackage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LocalSyncPackage> _parser = new pb::MessageParser<LocalSyncPackage>(() => new LocalSyncPackage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LocalSyncPackage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SyncPackage.SyncPackageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LocalSyncPackage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LocalSyncPackage(LocalSyncPackage other) : this() {
      eventID_ = other.eventID_;
      switch (other.ContentCase) {
        case ContentOneofCase.LobbySync:
          LobbySync = other.LobbySync.Clone();
          break;
        case ContentOneofCase.ClientSync:
          ClientSync = other.ClientSync.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LocalSyncPackage Clone() {
      return new LocalSyncPackage(this);
    }

    /// <summary>Field number for the "eventID" field.</summary>
    public const int EventIDFieldNumber = 1;
    private global::SyncPackage.LocalSyncEvent eventID_ = global::SyncPackage.LocalSyncEvent.LocalNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SyncPackage.LocalSyncEvent EventID {
      get { return eventID_; }
      set {
        eventID_ = value;
      }
    }

    /// <summary>Field number for the "lobbySync" field.</summary>
    public const int LobbySyncFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LobbySyncPackage.LobbySyncRequest LobbySync {
      get { return contentCase_ == ContentOneofCase.LobbySync ? (global::LobbySyncPackage.LobbySyncRequest) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.LobbySync;
      }
    }

    /// <summary>Field number for the "clientSync" field.</summary>
    public const int ClientSyncFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClientSyncPackage.ClientSyncRequest ClientSync {
      get { return contentCase_ == ContentOneofCase.ClientSync ? (global::ClientSyncPackage.ClientSyncRequest) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.ClientSync;
      }
    }

    private object content_;
    /// <summary>Enum of possible cases for the "content" oneof.</summary>
    public enum ContentOneofCase {
      None = 0,
      LobbySync = 2,
      ClientSync = 3,
    }
    private ContentOneofCase contentCase_ = ContentOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContentOneofCase ContentCase {
      get { return contentCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearContent() {
      contentCase_ = ContentOneofCase.None;
      content_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LocalSyncPackage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LocalSyncPackage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventID != other.EventID) return false;
      if (!object.Equals(LobbySync, other.LobbySync)) return false;
      if (!object.Equals(ClientSync, other.ClientSync)) return false;
      if (ContentCase != other.ContentCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventID != global::SyncPackage.LocalSyncEvent.LocalNone) hash ^= EventID.GetHashCode();
      if (contentCase_ == ContentOneofCase.LobbySync) hash ^= LobbySync.GetHashCode();
      if (contentCase_ == ContentOneofCase.ClientSync) hash ^= ClientSync.GetHashCode();
      hash ^= (int) contentCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EventID != global::SyncPackage.LocalSyncEvent.LocalNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventID);
      }
      if (contentCase_ == ContentOneofCase.LobbySync) {
        output.WriteRawTag(18);
        output.WriteMessage(LobbySync);
      }
      if (contentCase_ == ContentOneofCase.ClientSync) {
        output.WriteRawTag(26);
        output.WriteMessage(ClientSync);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EventID != global::SyncPackage.LocalSyncEvent.LocalNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventID);
      }
      if (contentCase_ == ContentOneofCase.LobbySync) {
        output.WriteRawTag(18);
        output.WriteMessage(LobbySync);
      }
      if (contentCase_ == ContentOneofCase.ClientSync) {
        output.WriteRawTag(26);
        output.WriteMessage(ClientSync);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventID != global::SyncPackage.LocalSyncEvent.LocalNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventID);
      }
      if (contentCase_ == ContentOneofCase.LobbySync) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LobbySync);
      }
      if (contentCase_ == ContentOneofCase.ClientSync) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClientSync);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LocalSyncPackage other) {
      if (other == null) {
        return;
      }
      if (other.EventID != global::SyncPackage.LocalSyncEvent.LocalNone) {
        EventID = other.EventID;
      }
      switch (other.ContentCase) {
        case ContentOneofCase.LobbySync:
          if (LobbySync == null) {
            LobbySync = new global::LobbySyncPackage.LobbySyncRequest();
          }
          LobbySync.MergeFrom(other.LobbySync);
          break;
        case ContentOneofCase.ClientSync:
          if (ClientSync == null) {
            ClientSync = new global::ClientSyncPackage.ClientSyncRequest();
          }
          ClientSync.MergeFrom(other.ClientSync);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EventID = (global::SyncPackage.LocalSyncEvent) input.ReadEnum();
            break;
          }
          case 18: {
            global::LobbySyncPackage.LobbySyncRequest subBuilder = new global::LobbySyncPackage.LobbySyncRequest();
            if (contentCase_ == ContentOneofCase.LobbySync) {
              subBuilder.MergeFrom(LobbySync);
            }
            input.ReadMessage(subBuilder);
            LobbySync = subBuilder;
            break;
          }
          case 26: {
            global::ClientSyncPackage.ClientSyncRequest subBuilder = new global::ClientSyncPackage.ClientSyncRequest();
            if (contentCase_ == ContentOneofCase.ClientSync) {
              subBuilder.MergeFrom(ClientSync);
            }
            input.ReadMessage(subBuilder);
            ClientSync = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EventID = (global::SyncPackage.LocalSyncEvent) input.ReadEnum();
            break;
          }
          case 18: {
            global::LobbySyncPackage.LobbySyncRequest subBuilder = new global::LobbySyncPackage.LobbySyncRequest();
            if (contentCase_ == ContentOneofCase.LobbySync) {
              subBuilder.MergeFrom(LobbySync);
            }
            input.ReadMessage(subBuilder);
            LobbySync = subBuilder;
            break;
          }
          case 26: {
            global::ClientSyncPackage.ClientSyncRequest subBuilder = new global::ClientSyncPackage.ClientSyncRequest();
            if (contentCase_ == ContentOneofCase.ClientSync) {
              subBuilder.MergeFrom(ClientSync);
            }
            input.ReadMessage(subBuilder);
            ClientSync = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 服务器发送给客户端的同步包
  /// </summary>
  public sealed partial class RemoteSyncPackage : pb::IMessage<RemoteSyncPackage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RemoteSyncPackage> _parser = new pb::MessageParser<RemoteSyncPackage>(() => new RemoteSyncPackage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RemoteSyncPackage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SyncPackage.SyncPackageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RemoteSyncPackage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RemoteSyncPackage(RemoteSyncPackage other) : this() {
      eventID_ = other.eventID_;
      switch (other.ContentCase) {
        case ContentOneofCase.LobbyPackage:
          LobbyPackage = other.LobbyPackage.Clone();
          break;
        case ContentOneofCase.ClientPackage:
          ClientPackage = other.ClientPackage.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RemoteSyncPackage Clone() {
      return new RemoteSyncPackage(this);
    }

    /// <summary>Field number for the "eventID" field.</summary>
    public const int EventIDFieldNumber = 1;
    private global::SyncPackage.RemoteSyncEvent eventID_ = global::SyncPackage.RemoteSyncEvent.RemoteNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SyncPackage.RemoteSyncEvent EventID {
      get { return eventID_; }
      set {
        eventID_ = value;
      }
    }

    /// <summary>Field number for the "lobbyPackage" field.</summary>
    public const int LobbyPackageFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LobbySyncPackage.LobbySyncResponse LobbyPackage {
      get { return contentCase_ == ContentOneofCase.LobbyPackage ? (global::LobbySyncPackage.LobbySyncResponse) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.LobbyPackage;
      }
    }

    /// <summary>Field number for the "clientPackage" field.</summary>
    public const int ClientPackageFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ClientSyncPackage.ClientSyncResponse ClientPackage {
      get { return contentCase_ == ContentOneofCase.ClientPackage ? (global::ClientSyncPackage.ClientSyncResponse) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.ClientPackage;
      }
    }

    private object content_;
    /// <summary>Enum of possible cases for the "content" oneof.</summary>
    public enum ContentOneofCase {
      None = 0,
      LobbyPackage = 2,
      ClientPackage = 3,
    }
    private ContentOneofCase contentCase_ = ContentOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContentOneofCase ContentCase {
      get { return contentCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearContent() {
      contentCase_ = ContentOneofCase.None;
      content_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RemoteSyncPackage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RemoteSyncPackage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventID != other.EventID) return false;
      if (!object.Equals(LobbyPackage, other.LobbyPackage)) return false;
      if (!object.Equals(ClientPackage, other.ClientPackage)) return false;
      if (ContentCase != other.ContentCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventID != global::SyncPackage.RemoteSyncEvent.RemoteNone) hash ^= EventID.GetHashCode();
      if (contentCase_ == ContentOneofCase.LobbyPackage) hash ^= LobbyPackage.GetHashCode();
      if (contentCase_ == ContentOneofCase.ClientPackage) hash ^= ClientPackage.GetHashCode();
      hash ^= (int) contentCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EventID != global::SyncPackage.RemoteSyncEvent.RemoteNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventID);
      }
      if (contentCase_ == ContentOneofCase.LobbyPackage) {
        output.WriteRawTag(18);
        output.WriteMessage(LobbyPackage);
      }
      if (contentCase_ == ContentOneofCase.ClientPackage) {
        output.WriteRawTag(26);
        output.WriteMessage(ClientPackage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EventID != global::SyncPackage.RemoteSyncEvent.RemoteNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventID);
      }
      if (contentCase_ == ContentOneofCase.LobbyPackage) {
        output.WriteRawTag(18);
        output.WriteMessage(LobbyPackage);
      }
      if (contentCase_ == ContentOneofCase.ClientPackage) {
        output.WriteRawTag(26);
        output.WriteMessage(ClientPackage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventID != global::SyncPackage.RemoteSyncEvent.RemoteNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventID);
      }
      if (contentCase_ == ContentOneofCase.LobbyPackage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LobbyPackage);
      }
      if (contentCase_ == ContentOneofCase.ClientPackage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClientPackage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RemoteSyncPackage other) {
      if (other == null) {
        return;
      }
      if (other.EventID != global::SyncPackage.RemoteSyncEvent.RemoteNone) {
        EventID = other.EventID;
      }
      switch (other.ContentCase) {
        case ContentOneofCase.LobbyPackage:
          if (LobbyPackage == null) {
            LobbyPackage = new global::LobbySyncPackage.LobbySyncResponse();
          }
          LobbyPackage.MergeFrom(other.LobbyPackage);
          break;
        case ContentOneofCase.ClientPackage:
          if (ClientPackage == null) {
            ClientPackage = new global::ClientSyncPackage.ClientSyncResponse();
          }
          ClientPackage.MergeFrom(other.ClientPackage);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EventID = (global::SyncPackage.RemoteSyncEvent) input.ReadEnum();
            break;
          }
          case 18: {
            global::LobbySyncPackage.LobbySyncResponse subBuilder = new global::LobbySyncPackage.LobbySyncResponse();
            if (contentCase_ == ContentOneofCase.LobbyPackage) {
              subBuilder.MergeFrom(LobbyPackage);
            }
            input.ReadMessage(subBuilder);
            LobbyPackage = subBuilder;
            break;
          }
          case 26: {
            global::ClientSyncPackage.ClientSyncResponse subBuilder = new global::ClientSyncPackage.ClientSyncResponse();
            if (contentCase_ == ContentOneofCase.ClientPackage) {
              subBuilder.MergeFrom(ClientPackage);
            }
            input.ReadMessage(subBuilder);
            ClientPackage = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EventID = (global::SyncPackage.RemoteSyncEvent) input.ReadEnum();
            break;
          }
          case 18: {
            global::LobbySyncPackage.LobbySyncResponse subBuilder = new global::LobbySyncPackage.LobbySyncResponse();
            if (contentCase_ == ContentOneofCase.LobbyPackage) {
              subBuilder.MergeFrom(LobbyPackage);
            }
            input.ReadMessage(subBuilder);
            LobbyPackage = subBuilder;
            break;
          }
          case 26: {
            global::ClientSyncPackage.ClientSyncResponse subBuilder = new global::ClientSyncPackage.ClientSyncResponse();
            if (contentCase_ == ContentOneofCase.ClientPackage) {
              subBuilder.MergeFrom(ClientPackage);
            }
            input.ReadMessage(subBuilder);
            ClientPackage = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
