// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SyncPackage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SyncPackage {

  /// <summary>Holder for reflection information generated from SyncPackage.proto</summary>
  public static partial class SyncPackageReflection {

    #region Descriptor
    /// <summary>File descriptor for SyncPackage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SyncPackageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFTeW5jUGFja2FnZS5wcm90bxILU3luY1BhY2thZ2UaF0JhdHRsZVN5bmNQ",
            "YWNrYWdlLnByb3RvGhZMb2JieVN5bmNQYWNrYWdlLnByb3RvGhRBY2tTeW5j",
            "UGFja2FnZS5wcm90byLzAQoQTG9jYWxTeW5jUGFja2FnZRIsCgdldmVudElE",
            "GAEgASgOMhsuU3luY1BhY2thZ2UuTG9jYWxTeW5jRXZlbnQSOgoKYmF0dGxl",
            "U3luYxgCIAEoCzIkLkJhdHRsZVN5bmNQYWNrYWdlLkJhdHRsZVN5bmNSZXF1",
            "ZXN0SAASNwoJbG9iYnlTeW5jGAMgASgLMiIuTG9iYnlTeW5jUGFja2FnZS5M",
            "b2JieVN5bmNSZXF1ZXN0SAASMQoHYWNrU3luYxgEIAEoCzIeLkFja1N5bmNQ",
            "YWNrYWdlLkFja1N5bmNSZXF1ZXN0SABCCQoHY29udGVudCL+AQoRUmVtb3Rl",
            "U3luY1BhY2thZ2USLQoHZXZlbnRJRBgBIAEoDjIcLlN5bmNQYWNrYWdlLlJl",
            "bW90ZVN5bmNFdmVudBI+Cg1iYXR0bGVQYWNrYWdlGAIgASgLMiUuQmF0dGxl",
            "U3luY1BhY2thZ2UuQmF0dGxlU3luY1Jlc3BvbnNlSAASOwoMbG9iYnlQYWNr",
            "YWdlGAMgASgLMiMuTG9iYnlTeW5jUGFja2FnZS5Mb2JieVN5bmNSZXNwb25z",
            "ZUgAEjIKB2Fja1N5bmMYBCABKAsyHy5BY2tTeW5jUGFja2FnZS5BY2tTeW5j",
            "UmVzcG9uc2VIAEIJCgdjb250ZW50KlUKDkxvY2FsU3luY0V2ZW50Eg4KCkxv",
            "Y2FsX05vbmUQABIRCg1CYXR0bGVSZXF1ZXN0EAESEAoMTG9iYnlSZXF1ZXN0",
            "EAISDgoKQWNrUmVxdWVzdBADKloKD1JlbW90ZVN5bmNFdmVudBIPCgtSZW1v",
            "dGVfTm9uZRAAEhIKDkJhdHRsZVJlc3BvbnNlEAESEQoNTG9iYnlSZXNwb25z",
            "ZRACEg8KC0Fja1Jlc3BvbnNlEANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::BattleSyncPackage.BattleSyncPackageReflection.Descriptor, global::LobbySyncPackage.LobbySyncPackageReflection.Descriptor, global::AckSyncPackage.AckSyncPackageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SyncPackage.LocalSyncEvent), typeof(global::SyncPackage.RemoteSyncEvent), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SyncPackage.LocalSyncPackage), global::SyncPackage.LocalSyncPackage.Parser, new[]{ "EventID", "BattleSync", "LobbySync", "AckSync" }, new[]{ "Content" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SyncPackage.RemoteSyncPackage), global::SyncPackage.RemoteSyncPackage.Parser, new[]{ "EventID", "BattlePackage", "LobbyPackage", "AckSync" }, new[]{ "Content" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// ==================================================
  ///客户端->服务端同步包汇总
  ///================================================== 
  /// </summary>
  public enum LocalSyncEvent {
    [pbr::OriginalName("Local_None")] LocalNone = 0,
    [pbr::OriginalName("BattleRequest")] BattleRequest = 1,
    [pbr::OriginalName("LobbyRequest")] LobbyRequest = 2,
    [pbr::OriginalName("AckRequest")] AckRequest = 3,
  }

  /// <summary>
  /// ==================================================
  ///服务端->客户端同步包汇总
  ///================================================== 
  /// </summary>
  public enum RemoteSyncEvent {
    [pbr::OriginalName("Remote_None")] RemoteNone = 0,
    [pbr::OriginalName("BattleResponse")] BattleResponse = 1,
    [pbr::OriginalName("LobbyResponse")] LobbyResponse = 2,
    [pbr::OriginalName("AckResponse")] AckResponse = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 客户端发送给服务器的同步包
  /// </summary>
  public sealed partial class LocalSyncPackage : pb::IMessage<LocalSyncPackage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LocalSyncPackage> _parser = new pb::MessageParser<LocalSyncPackage>(() => new LocalSyncPackage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LocalSyncPackage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SyncPackage.SyncPackageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LocalSyncPackage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LocalSyncPackage(LocalSyncPackage other) : this() {
      eventID_ = other.eventID_;
      switch (other.ContentCase) {
        case ContentOneofCase.BattleSync:
          BattleSync = other.BattleSync.Clone();
          break;
        case ContentOneofCase.LobbySync:
          LobbySync = other.LobbySync.Clone();
          break;
        case ContentOneofCase.AckSync:
          AckSync = other.AckSync.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LocalSyncPackage Clone() {
      return new LocalSyncPackage(this);
    }

    /// <summary>Field number for the "eventID" field.</summary>
    public const int EventIDFieldNumber = 1;
    private global::SyncPackage.LocalSyncEvent eventID_ = global::SyncPackage.LocalSyncEvent.LocalNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SyncPackage.LocalSyncEvent EventID {
      get { return eventID_; }
      set {
        eventID_ = value;
      }
    }

    /// <summary>Field number for the "battleSync" field.</summary>
    public const int BattleSyncFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::BattleSyncPackage.BattleSyncRequest BattleSync {
      get { return contentCase_ == ContentOneofCase.BattleSync ? (global::BattleSyncPackage.BattleSyncRequest) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.BattleSync;
      }
    }

    /// <summary>Field number for the "lobbySync" field.</summary>
    public const int LobbySyncFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LobbySyncPackage.LobbySyncRequest LobbySync {
      get { return contentCase_ == ContentOneofCase.LobbySync ? (global::LobbySyncPackage.LobbySyncRequest) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.LobbySync;
      }
    }

    /// <summary>Field number for the "ackSync" field.</summary>
    public const int AckSyncFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AckSyncPackage.AckSyncRequest AckSync {
      get { return contentCase_ == ContentOneofCase.AckSync ? (global::AckSyncPackage.AckSyncRequest) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.AckSync;
      }
    }

    private object content_;
    /// <summary>Enum of possible cases for the "content" oneof.</summary>
    public enum ContentOneofCase {
      None = 0,
      BattleSync = 2,
      LobbySync = 3,
      AckSync = 4,
    }
    private ContentOneofCase contentCase_ = ContentOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContentOneofCase ContentCase {
      get { return contentCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearContent() {
      contentCase_ = ContentOneofCase.None;
      content_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LocalSyncPackage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LocalSyncPackage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventID != other.EventID) return false;
      if (!object.Equals(BattleSync, other.BattleSync)) return false;
      if (!object.Equals(LobbySync, other.LobbySync)) return false;
      if (!object.Equals(AckSync, other.AckSync)) return false;
      if (ContentCase != other.ContentCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventID != global::SyncPackage.LocalSyncEvent.LocalNone) hash ^= EventID.GetHashCode();
      if (contentCase_ == ContentOneofCase.BattleSync) hash ^= BattleSync.GetHashCode();
      if (contentCase_ == ContentOneofCase.LobbySync) hash ^= LobbySync.GetHashCode();
      if (contentCase_ == ContentOneofCase.AckSync) hash ^= AckSync.GetHashCode();
      hash ^= (int) contentCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EventID != global::SyncPackage.LocalSyncEvent.LocalNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventID);
      }
      if (contentCase_ == ContentOneofCase.BattleSync) {
        output.WriteRawTag(18);
        output.WriteMessage(BattleSync);
      }
      if (contentCase_ == ContentOneofCase.LobbySync) {
        output.WriteRawTag(26);
        output.WriteMessage(LobbySync);
      }
      if (contentCase_ == ContentOneofCase.AckSync) {
        output.WriteRawTag(34);
        output.WriteMessage(AckSync);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EventID != global::SyncPackage.LocalSyncEvent.LocalNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventID);
      }
      if (contentCase_ == ContentOneofCase.BattleSync) {
        output.WriteRawTag(18);
        output.WriteMessage(BattleSync);
      }
      if (contentCase_ == ContentOneofCase.LobbySync) {
        output.WriteRawTag(26);
        output.WriteMessage(LobbySync);
      }
      if (contentCase_ == ContentOneofCase.AckSync) {
        output.WriteRawTag(34);
        output.WriteMessage(AckSync);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventID != global::SyncPackage.LocalSyncEvent.LocalNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventID);
      }
      if (contentCase_ == ContentOneofCase.BattleSync) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BattleSync);
      }
      if (contentCase_ == ContentOneofCase.LobbySync) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LobbySync);
      }
      if (contentCase_ == ContentOneofCase.AckSync) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AckSync);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LocalSyncPackage other) {
      if (other == null) {
        return;
      }
      if (other.EventID != global::SyncPackage.LocalSyncEvent.LocalNone) {
        EventID = other.EventID;
      }
      switch (other.ContentCase) {
        case ContentOneofCase.BattleSync:
          if (BattleSync == null) {
            BattleSync = new global::BattleSyncPackage.BattleSyncRequest();
          }
          BattleSync.MergeFrom(other.BattleSync);
          break;
        case ContentOneofCase.LobbySync:
          if (LobbySync == null) {
            LobbySync = new global::LobbySyncPackage.LobbySyncRequest();
          }
          LobbySync.MergeFrom(other.LobbySync);
          break;
        case ContentOneofCase.AckSync:
          if (AckSync == null) {
            AckSync = new global::AckSyncPackage.AckSyncRequest();
          }
          AckSync.MergeFrom(other.AckSync);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EventID = (global::SyncPackage.LocalSyncEvent) input.ReadEnum();
            break;
          }
          case 18: {
            global::BattleSyncPackage.BattleSyncRequest subBuilder = new global::BattleSyncPackage.BattleSyncRequest();
            if (contentCase_ == ContentOneofCase.BattleSync) {
              subBuilder.MergeFrom(BattleSync);
            }
            input.ReadMessage(subBuilder);
            BattleSync = subBuilder;
            break;
          }
          case 26: {
            global::LobbySyncPackage.LobbySyncRequest subBuilder = new global::LobbySyncPackage.LobbySyncRequest();
            if (contentCase_ == ContentOneofCase.LobbySync) {
              subBuilder.MergeFrom(LobbySync);
            }
            input.ReadMessage(subBuilder);
            LobbySync = subBuilder;
            break;
          }
          case 34: {
            global::AckSyncPackage.AckSyncRequest subBuilder = new global::AckSyncPackage.AckSyncRequest();
            if (contentCase_ == ContentOneofCase.AckSync) {
              subBuilder.MergeFrom(AckSync);
            }
            input.ReadMessage(subBuilder);
            AckSync = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EventID = (global::SyncPackage.LocalSyncEvent) input.ReadEnum();
            break;
          }
          case 18: {
            global::BattleSyncPackage.BattleSyncRequest subBuilder = new global::BattleSyncPackage.BattleSyncRequest();
            if (contentCase_ == ContentOneofCase.BattleSync) {
              subBuilder.MergeFrom(BattleSync);
            }
            input.ReadMessage(subBuilder);
            BattleSync = subBuilder;
            break;
          }
          case 26: {
            global::LobbySyncPackage.LobbySyncRequest subBuilder = new global::LobbySyncPackage.LobbySyncRequest();
            if (contentCase_ == ContentOneofCase.LobbySync) {
              subBuilder.MergeFrom(LobbySync);
            }
            input.ReadMessage(subBuilder);
            LobbySync = subBuilder;
            break;
          }
          case 34: {
            global::AckSyncPackage.AckSyncRequest subBuilder = new global::AckSyncPackage.AckSyncRequest();
            if (contentCase_ == ContentOneofCase.AckSync) {
              subBuilder.MergeFrom(AckSync);
            }
            input.ReadMessage(subBuilder);
            AckSync = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 服务器发送给客户端的同步包
  /// </summary>
  public sealed partial class RemoteSyncPackage : pb::IMessage<RemoteSyncPackage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RemoteSyncPackage> _parser = new pb::MessageParser<RemoteSyncPackage>(() => new RemoteSyncPackage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RemoteSyncPackage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SyncPackage.SyncPackageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RemoteSyncPackage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RemoteSyncPackage(RemoteSyncPackage other) : this() {
      eventID_ = other.eventID_;
      switch (other.ContentCase) {
        case ContentOneofCase.BattlePackage:
          BattlePackage = other.BattlePackage.Clone();
          break;
        case ContentOneofCase.LobbyPackage:
          LobbyPackage = other.LobbyPackage.Clone();
          break;
        case ContentOneofCase.AckSync:
          AckSync = other.AckSync.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RemoteSyncPackage Clone() {
      return new RemoteSyncPackage(this);
    }

    /// <summary>Field number for the "eventID" field.</summary>
    public const int EventIDFieldNumber = 1;
    private global::SyncPackage.RemoteSyncEvent eventID_ = global::SyncPackage.RemoteSyncEvent.RemoteNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::SyncPackage.RemoteSyncEvent EventID {
      get { return eventID_; }
      set {
        eventID_ = value;
      }
    }

    /// <summary>Field number for the "battlePackage" field.</summary>
    public const int BattlePackageFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::BattleSyncPackage.BattleSyncResponse BattlePackage {
      get { return contentCase_ == ContentOneofCase.BattlePackage ? (global::BattleSyncPackage.BattleSyncResponse) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.BattlePackage;
      }
    }

    /// <summary>Field number for the "lobbyPackage" field.</summary>
    public const int LobbyPackageFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LobbySyncPackage.LobbySyncResponse LobbyPackage {
      get { return contentCase_ == ContentOneofCase.LobbyPackage ? (global::LobbySyncPackage.LobbySyncResponse) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.LobbyPackage;
      }
    }

    /// <summary>Field number for the "ackSync" field.</summary>
    public const int AckSyncFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AckSyncPackage.AckSyncResponse AckSync {
      get { return contentCase_ == ContentOneofCase.AckSync ? (global::AckSyncPackage.AckSyncResponse) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.AckSync;
      }
    }

    private object content_;
    /// <summary>Enum of possible cases for the "content" oneof.</summary>
    public enum ContentOneofCase {
      None = 0,
      BattlePackage = 2,
      LobbyPackage = 3,
      AckSync = 4,
    }
    private ContentOneofCase contentCase_ = ContentOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContentOneofCase ContentCase {
      get { return contentCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearContent() {
      contentCase_ = ContentOneofCase.None;
      content_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RemoteSyncPackage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RemoteSyncPackage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventID != other.EventID) return false;
      if (!object.Equals(BattlePackage, other.BattlePackage)) return false;
      if (!object.Equals(LobbyPackage, other.LobbyPackage)) return false;
      if (!object.Equals(AckSync, other.AckSync)) return false;
      if (ContentCase != other.ContentCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventID != global::SyncPackage.RemoteSyncEvent.RemoteNone) hash ^= EventID.GetHashCode();
      if (contentCase_ == ContentOneofCase.BattlePackage) hash ^= BattlePackage.GetHashCode();
      if (contentCase_ == ContentOneofCase.LobbyPackage) hash ^= LobbyPackage.GetHashCode();
      if (contentCase_ == ContentOneofCase.AckSync) hash ^= AckSync.GetHashCode();
      hash ^= (int) contentCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EventID != global::SyncPackage.RemoteSyncEvent.RemoteNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventID);
      }
      if (contentCase_ == ContentOneofCase.BattlePackage) {
        output.WriteRawTag(18);
        output.WriteMessage(BattlePackage);
      }
      if (contentCase_ == ContentOneofCase.LobbyPackage) {
        output.WriteRawTag(26);
        output.WriteMessage(LobbyPackage);
      }
      if (contentCase_ == ContentOneofCase.AckSync) {
        output.WriteRawTag(34);
        output.WriteMessage(AckSync);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EventID != global::SyncPackage.RemoteSyncEvent.RemoteNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventID);
      }
      if (contentCase_ == ContentOneofCase.BattlePackage) {
        output.WriteRawTag(18);
        output.WriteMessage(BattlePackage);
      }
      if (contentCase_ == ContentOneofCase.LobbyPackage) {
        output.WriteRawTag(26);
        output.WriteMessage(LobbyPackage);
      }
      if (contentCase_ == ContentOneofCase.AckSync) {
        output.WriteRawTag(34);
        output.WriteMessage(AckSync);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventID != global::SyncPackage.RemoteSyncEvent.RemoteNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventID);
      }
      if (contentCase_ == ContentOneofCase.BattlePackage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BattlePackage);
      }
      if (contentCase_ == ContentOneofCase.LobbyPackage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LobbyPackage);
      }
      if (contentCase_ == ContentOneofCase.AckSync) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AckSync);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RemoteSyncPackage other) {
      if (other == null) {
        return;
      }
      if (other.EventID != global::SyncPackage.RemoteSyncEvent.RemoteNone) {
        EventID = other.EventID;
      }
      switch (other.ContentCase) {
        case ContentOneofCase.BattlePackage:
          if (BattlePackage == null) {
            BattlePackage = new global::BattleSyncPackage.BattleSyncResponse();
          }
          BattlePackage.MergeFrom(other.BattlePackage);
          break;
        case ContentOneofCase.LobbyPackage:
          if (LobbyPackage == null) {
            LobbyPackage = new global::LobbySyncPackage.LobbySyncResponse();
          }
          LobbyPackage.MergeFrom(other.LobbyPackage);
          break;
        case ContentOneofCase.AckSync:
          if (AckSync == null) {
            AckSync = new global::AckSyncPackage.AckSyncResponse();
          }
          AckSync.MergeFrom(other.AckSync);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EventID = (global::SyncPackage.RemoteSyncEvent) input.ReadEnum();
            break;
          }
          case 18: {
            global::BattleSyncPackage.BattleSyncResponse subBuilder = new global::BattleSyncPackage.BattleSyncResponse();
            if (contentCase_ == ContentOneofCase.BattlePackage) {
              subBuilder.MergeFrom(BattlePackage);
            }
            input.ReadMessage(subBuilder);
            BattlePackage = subBuilder;
            break;
          }
          case 26: {
            global::LobbySyncPackage.LobbySyncResponse subBuilder = new global::LobbySyncPackage.LobbySyncResponse();
            if (contentCase_ == ContentOneofCase.LobbyPackage) {
              subBuilder.MergeFrom(LobbyPackage);
            }
            input.ReadMessage(subBuilder);
            LobbyPackage = subBuilder;
            break;
          }
          case 34: {
            global::AckSyncPackage.AckSyncResponse subBuilder = new global::AckSyncPackage.AckSyncResponse();
            if (contentCase_ == ContentOneofCase.AckSync) {
              subBuilder.MergeFrom(AckSync);
            }
            input.ReadMessage(subBuilder);
            AckSync = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EventID = (global::SyncPackage.RemoteSyncEvent) input.ReadEnum();
            break;
          }
          case 18: {
            global::BattleSyncPackage.BattleSyncResponse subBuilder = new global::BattleSyncPackage.BattleSyncResponse();
            if (contentCase_ == ContentOneofCase.BattlePackage) {
              subBuilder.MergeFrom(BattlePackage);
            }
            input.ReadMessage(subBuilder);
            BattlePackage = subBuilder;
            break;
          }
          case 26: {
            global::LobbySyncPackage.LobbySyncResponse subBuilder = new global::LobbySyncPackage.LobbySyncResponse();
            if (contentCase_ == ContentOneofCase.LobbyPackage) {
              subBuilder.MergeFrom(LobbyPackage);
            }
            input.ReadMessage(subBuilder);
            LobbyPackage = subBuilder;
            break;
          }
          case 34: {
            global::AckSyncPackage.AckSyncResponse subBuilder = new global::AckSyncPackage.AckSyncResponse();
            if (contentCase_ == ContentOneofCase.AckSync) {
              subBuilder.MergeFrom(AckSync);
            }
            input.ReadMessage(subBuilder);
            AckSync = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
